### PR TITLE
Allow MOTD to be tested with appropriate placeholders instead of ignoring completely #4543

### LINKED ISSUE #4543: Allow MOTD to be tested with appropriate placeholders instead of ignoring completely
One of the TODOs I left in #4535.
#3932 is solved by ignoring MOTD entirely. I don't like this solution because then we have no means to test it. Unlike tooltips which are truly random, MOTD is not.
With appropriate handling via God mode or `HtmlHelper` it should be doable with relative ease.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #4543 
Tested with two different MOTD URLs, worked smoothly.

### CODE REVIEW

**Comment by kanghj** [comment]
Have you tested if it works if there isn't a MOTD?

**Comment by wkurniawan07** [comment]
Tested with empty, invalid (this would include valid but not loaded due to ajax error), and valid MOTD. All worked.

**Comment by kanghj** [comment]
Ok, it looks good now then

**Comment by damithc** [comment]
How come this PR is still open?

**Comment by thyageshm** [comment]
sir, I think this one is already closed. The status is 'MERGED'

**Comment by wkurniawan07** [comment]
This PR has been merged for more than a month now.

**Comment by damithc** [comment]
Yes, for some reason it showed as 'open' in HubTurbo.

**Pull request merged**
