### PR TITLE
Cannot click MCQ options when there are more than 10 team members #3110

### LINKED ISSUE #3110: Cannot click MCQ options when there are more than 10 team members
There is a course with more than 10 team members. An MCQ question requires evaluating all team members. Options cannot be clicked for the 11th member onwards. Tried both Chrome and IE.
image

### PR DESCRIPTION
**Pull request by LowWeiLin**
Fixes #3110

@damithc

### CODE REVIEW

**Comment by damithc** [comment]
No longer VERY urgent. Take your time to ensure the fix is fine. Go ahead and merge after that.

**Comment by LowWeiLin** [comment]
Fixed the cause of the bug, where a function is binded to an element more than once.

**Comment by damithc** [comment]
Confirm the bug surfaces only if there are more than 10 recipients?

**Comment by LowWeiLin** [comment]
Yes, this is due to the line:
radioButtons[id] = $("[name^=" + id + "]"); 

The ^= operator matches names that begin with a certain string.
So "responsetext-1-1" results in a match for "responsetext-1-1" as well as "responsetext-1-10", 11,12...
Causing the bug when there are more than 10 recipients.

**Comment by kanghj** [comment]
There might be other places in the code where a similar bug may occur. We should check and change other jquery selectors to use exact match, if required. For example, in prepareContribQuestions, a similar selector is used, although it's only used for the UI now.
<code> var dropdown = $("[name^='responsetext-" + qnNum + "-" + k + "']");</code>

**Comment by damithc** [comment]
Classic gotcha :-p
Yes @kanghj, we should do a sweep for similar bugs. May be create an issue for that?

**Pull request merged**
