### PR TITLE
admin sessions page: show more stats #4598

### LINKED ISSUE #4598: admin sessions page: show more stats
We can show more stats here: e.g. number of institutes, number of open sessions, etc.
image

### PR DESCRIPTION
**Pull request by sundychenD**
Fix #4598 
Change "Total" in admin status to "Ongoing"
Add "Opened" field which shows total number of sessions that are under "Opened" status.
Add "Institutions" field which shows total number of institutions (exclude "unknown"). 
screen shot 2015-12-27 at 11 16 41 pm

### CODE REVIEW

**Comment by damithc** [comment]
Keep the `Total` as well. May be show all in one line (to save vertical space)?

**Comment by sundychenD** [comment]
Sure, the horizontal version is shown bellow:
screen shot 2015-12-28 at 11 11 47 am

**Comment by damithc** [comment]
Why not show the total for other status? e.g. waiting to open

**Comment by sundychenD** [comment]
They are also achievable, but are we suppose to display all the status? there are 8 status in total, "isClosed, isOpened, isInGracePeriod, isWaitingToOpen, isVisible, isPublished, isManuallyPublished, isPrivateSession"

**Comment by damithc** [comment]
This three would do: isClosed, isOpened, isWaitingToOpen

**Comment by sundychenD** [comment]
4 Status "Total, Open, Closed, WaitToOpen" + 1 Statistics "Institutes" has been added.
screen shot 2015-12-29 at 3 27 56 pm

**Comment by damithc** [comment]
UI-wise, you can combine lines 1-2 and lines 3-4, to reduce vertical scrolling. After that, we can wait for a developer to review the code.

**Comment by sundychenD** [comment]
Combine lines 3-4 would give the UI shown below:
screen shot 2015-12-29 at 5 51 17 pm

How about leave line 3 alone? As line 3 also displays the same categories of data as line 1-2
screen shot 2015-12-29 at 3 27 56 pm

**Comment by damithc** [comment]
Sure, go with the 2nd option.

**Comment by bamboo3250** [comment]
Goob job! I see no problem. Good to merge :+1:

**Comment by damithc** [comment]
Khanh I think you'll have to merge yourself.



-- 
Sent from a mobile device.

**Comment by bamboo3250** [comment]
Ah you are right. I'll merge after finishing running the test suit.

**Pull request merged**
