### PR TITLE
Godmode does not work properly for Ajax Html comparison #4324

### LINKED ISSUE #4324: Godmode does not work properly for Ajax Html comparison
The Godmode function call in verifyHtmlAjax(String filePath) - Line 873 method is passing the wrong parameter value for isHtmlPart

### PR DESCRIPTION
**Pull request by thyageshm**
fixes #4324 
@kanghj review this?

### CODE REVIEW

**Comment by thyageshm** [comment]
The Ajax Html Pages had been generated properly earlier in #4237 as the change that caused this problem was introduced after all AJAX pages were regenerated...

**Comment by thyageshm** [comment]
@LowWeiLin could you also take a look?

**Comment by thyageshm** [comment]
@kanghj @damithc I believe this will handle the unusual behaviour of godmode in the Ajax pages of #4322

**Comment by kanghj** [comment]
Yes, the behaviour of godmode is now correct on #4322.

**Comment by thyageshm** [comment]
@kanghj so shall I merge this in now?

**Comment by kanghj** [comment]
Yup, let's merge this in

**Pull request merged**
