### PR TITLE
Title should not be data-original on our HTML template #3983

### LINKED ISSUE #3983: Title should not be data-original on our HTML template
Jumping the gun by doing what bootstrap does, we should just leave it as title="tooltip text" and let the bootstrap .tooltip() function do it's job.

Will upload a screenshot when I can.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #3983

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@bamboo3250 Not sure what is there to review, though, but help me review :p

**Comment by bamboo3250** [comment]
There is "data-original-title" in `feedbackResponseComments.js` and `instructorFeedbackEdit.js`. I think we should change them as well.

**Comment by wkurniawan07** [comment]
`data-original-title` in js files is correctly used because after bootstrapping the attribute to target is no longer `title`, but `data-original-title`.

**Comment by bamboo3250** [comment]
then it's good to merged :+1:

**Pull request merged**
