### PR TITLE
Fix JSTL-Dev due to FRC standardization

### PR DESCRIPTION
**Pull request by wkurniawan07**
JSTL-Dev is currently _not_ green. This fix is necessary to make it green.
If somebody is willing to review.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
On hold until #3893 is merged.

**Comment by wkurniawan07** [comment]
Actually #3893 only affects in the way fixed by the last commit, so even before I merged master in, I can say that this will be the correct fix already.

**Comment by wkurniawan07** [comment]
@MrFool can help review? This should be very fast.

**Comment by junhaoyap** [comment]
Looks good, this fixes JSTL-Dev to be green ya?

**Comment by wkurniawan07** [comment]
Yeah!

**Pull request merged**
