### PR TITLE
Update documentation to reflect JSTL usage #4076

### LINKED ISSUE #4076: Update documentation to reflect JSTL usage
Go through documentation (dev guide etc.) and update where necessary to reflect the state of the code after JSTL migration

### PR DESCRIPTION
**Pull request by kanghj**
Fixes #4076 

I will need to update some of the google docs after this, like the Contributor Orientation Guide and the Resources Bin.

### CODE REVIEW

**Comment by damithc** [comment]
For review or still ongoing?

**Comment by damithc** [comment]
Request access for those Google docs and I'll grant access.

**Comment by kanghj** [comment]
For review, I forgot to add the label

**Comment by kanghj** [comment]
Will update those google docs now, seems like I have access to them already

**Comment by kanghj** [comment]
Updated the docs. Added the links @yj-soh gave to us for JSTL in the resources bin.

**Pull request merged**
