### PR TITLE
Typo in devman.html #3027 

### LINKED ISSUE #3027: Typo in devman.html
Under the Design, UI section, in Request Flow:
 
7) ...creates a ShowPageResult object by encolosing the PageData object...
"encolosing" should be enclosing.

8) ControllerServlert "sends" the result....
"ControllerServlert" should be "ControllerServlet".

"Things to note" part, there is a sentence that says "Server processes the request separately (creates a ShowPageResult object but and a PageData object) and returns the 'courses' page." 
I think it should be "but no PageData object" instead.

### PR DESCRIPTION
**Pull request by halfdreamer**
Fixes #3027

### CODE REVIEW

**Comment by LowWeiLin** [comment]
Great! Looks good to me.
@damithc

**Comment by damithc** [comment]
Go ahead and merge WeiLin

**Comment by LowWeiLin** [comment]
@halfdreamer Just a comment, the time of your commits seem to be way ahead(by one day). Is the time set correctly on your computer or is this just a time zone issue?

**Comment by halfdreamer** [comment]
@LowWeiLin looks like my system time was wrong at the time of the commit...

**Comment by damithc** [comment]
So Git remote repo can be fooled by changing the local computer time?
That's interesting :-p

**Pull request merged**
