### PR TITLE
Make the time stamp in emails unambiguous #4419

### LINKED ISSUE #4419: Make the time stamp in emails unambiguous
There is a user claiming that the email said 0600 and he wasn't sure it was am or pm. Should we use a  clearer time format in emails?

### PR DESCRIPTION
**Pull request by LowWeiLin**
Fixes #4419

### CODE REVIEW

**Comment by damithc** [comment]
There are few other places where the time is displayed in a not-ideal format e.g. submission page.
It's even worse when the instructor get confused and set the wrong time (set 6am when he meant 6pm). But that can be fixed as a separate issue.

**Comment by damithc** [comment]
Actually, in both cases detected, it was the instructor who made the first mistake. Students simply missed the deadline because they did not realize the instructor's mistake.

**Comment by LowWeiLin** [comment]
Is there a list of places we should use the 12H format? Or do we simply change all dates to 12H format?

**Comment by damithc** [comment]
I guess better to use 12h format in all places. Will that mess up sorting when it is shown in a column? @ashrayjain

**Comment by damithc** [comment]
Have we created another issue to fix this in other places?

**Comment by LowWeiLin** [comment]
Changing the timestamp may not be enough?
In the instructor feedback creation/edit form, the dropdown is in 24H too. I'm not sure how it can be made clearer so that the instructors do not make a mistake.
image

**Pull request merged**
