### PR TITLE
Update DataMigrationEvaluationsToFeedbackSessions to delete evaluations #3365

### LINKED ISSUE #3365: Update DataMigrationEvaluationsToFeedbackSessions to delete evaluations
Need to check if the script is still correct, print a message if there are clashes in feedback session names. Delete the evaluation after creating the feedback session for it.

### PR DESCRIPTION
**Pull request by kanghj**
Fixes #3365

I used createFeedbackQuestionForTemplate, which does not check for the existence of the feedback session, instead of createFeedbackQuestion in case of problems with eventual consistency.

DataMigrationForResponseRate should be run after running DataMigrationEvaluationsToFeedbackSessions should update the response rate.

### CODE REVIEW

**Comment by damithc** [comment]
Go ahead and merge.

**Comment by kanghj** [comment]
Added a flag for previewing if there are name clashes

**Comment by kanghj** [comment]
Updated.

**Comment by kanghj** [comment]
Updated with batch inserts. The ids seem to be assigned only after makePersistent has been called, so the questions need to inserted first before creating the responses.

**Comment by damithc** [comment]
This one is faster. Took less than half the time the previous version took.

**Pull request merged**
