### PR TITLE
Admin UI tests in full run failing due to admin username contamination #4377

### LINKED ISSUE #4377: Admin UI tests in full run failing due to admin username contamination
The actual cause has not been remedied up to now. Removing HTML comparisons imho is an overkill solution (although it works and I won't say no to it, hey no HTML comparison means it's faster). Here's the actual cause: _almost every single_ UI test has admin login in it. As the result, the admin UI tests are badly contaminated. So the true solution is to allow an alternative login with _no_ admin privilege, and reserve the admin privilege only to admin UI tests. It should make sense -- there's supposedly only one admin for the app!

P.S. If we still go into the path of removing all HTML comparisons, at least fixing this will make life easier until all the comparisons are gone :p

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #4377 
As discussed, although this solves the problem at hand, removing the HTML comparisons altogether may be better for the long run. In that case, at least this will suppress all the failures until the point where all HTML comparisons are gone.
P.S. this hasn't been tested in staging yet.

### CODE REVIEW

**Comment by damithc** [comment]
If you want to do it this way, extract these three lines into one place and explain the rationale in the extracted method. Otherwise it is duplication and also it looks odd why there is a sequence of login->logout->login

**Comment by wkurniawan07** [comment]
Worked in staging, although I can't finish the full test run (quota busted slightly after halfway the run).

**Comment by damithc** [comment]
It's ok if all pass in dev server and admin tests pass in staging. I'll do
a full run on staging and report after this release.

**Comment by wkurniawan07** [comment]
I rebased and made some changes, can review again?

**Comment by bamboo3250** [comment]
looks okay, can merge now.

**Pull request merged**
