### PR TITLE
Add AJAX request error handling for instructorFeedbacksAjax.js #4387 

### LINKED ISSUE #4387: Add AJAX request error handling for instructorFeedbacksAjax.js
Part of #4082 

**instructorFeedbacksAjax.js**

**Success:** Appends list of sessions onto page on page load.
**Failure:** Loading spinner remains, nothing else happens.

This should not even happen unless the server goes down with the page loaded halfway.

An error message, where the list would usually be, should be shown using the status message div to get the user to refresh the page.

### PR DESCRIPTION
**Pull request by yj-soh**
Fixes #4387

### CODE REVIEW

**Comment by imouto1994** [comment]
In the Instructor Courses page, the way handle is to show that `Courses could not be loaded. Please click here to retry` to allow the user to retry sending AJAX request instead of reloading the whole page.

**Comment by yj-soh** [comment]
The handling's from the discussion in #4082.
We should probably standardise it, but which way should we standardise it with?
#4340 isn't merged yet, so I'm not sure if we can count that.

**Comment by imouto1994** [comment]
@damithc Can you give your decision on this? Should we have some kind of standardisation?

**Comment by damithc** [comment]
I'm fine with what @imouto1994 suggested unless @yj-soh has a better idea.

**Comment by yj-soh** [comment]
@imouto1994 Done, please review again.

**Comment by imouto1994** [comment]
Can you add a test case when the AJAX request fails ?

**Comment by yj-soh** [comment]
@imouto1994 Test added.

**Comment by imouto1994** [comment]
Looks good! Make sure all test cases passed before merging

**Pull request merged**
