### PR TITLE
StudentHomePageUiTest fails often at persistence check #3259

### LINKED ISSUE #3259: StudentHomePageUiTest fails often at persistence check
studenthomepagefail
Those who are on TEAMMATES for long enough shouldn't be stranger to this.
I only bring this up now because I've found the fix. Will push it in around 5 minutes.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #3259
Dev green and ready for immediate review

### CODE REVIEW

**Comment by wkurniawan07** [comment]
To understand how the solution is as simple as adding two lines, let's see how the issue originates. Notice this code in `StudentHomePageAction`:

The code block I highlighted ensures that the browser page shows the evaluation details in sorted order.
However, in persistence checking, catch block will be executed instead. Just a few lines down...

Notice anything missing? Yes, the sorting part.
How come the test page still shows in sorted order, consistently? The answer lies in the studentHome.js:
```
$(document).ready(function(){
    $('.table').each(function(){
        sortTable($(this),2,null,true, 1);
    });
});
```

**Comment by LowWeiLin** [comment]
Is the JS sorting function still necessary? If not, can remove it.

**Comment by wkurniawan07** [comment]
I guess it's still, because the way the studentHome.jsp works is, for each course, by appending data from `EvaluationDetailsBundle` (sorted) and `FeedbackSessionDetailsBundle` (sorted) sequentially, then sorting them altogether based on the deadline. Like this:
```
for (EvaluationDetailsBundle edd : courseDetails.evaluations) {
    sessionIdx++;
    // add the HTML table corresponding to the data
}
for (FeedbackSessionDetailsBundle fsd : courseDetails.feedbackSessions) {
    sessionIdx++;
    // add the HTML table corresponding to the data
}
```
After which, the JS will take action.

**Comment by LowWeiLin** [comment]
Great! I don;t see this failing now.

**Comment by wkurniawan07** [comment]
This one and the one I fixed in #3254 are now 100% pass except for extraordinary circumstances :v: 
Guess for the next few days I'll try to fix more problematic tests, then.

**Comment by LowWeiLin** [comment]
InstructorHomePageUiTest failed once for me though, although it is a different problem, where some element could not be found and timed out. Yes, it would be best if all tests can pass in one run!

**Pull request merged**
