### PR TITLE
settingUp.md: Improve the instructions for getting join link for student login

### PR DESCRIPTION
**Pull request by jp111**
Please review #3131

### CODE REVIEW

**Comment by kanghj** [comment]
The name of the pull request is incorrect.

**Comment by jp111** [comment]
Sorry, I didn't get you. Do you mean that the request number has to be changed in commit?

**Comment by jp111** [comment]
Updated the name.

**Comment by kanghj** [comment]
@jp111, the name of the pull request is still missing the number of the issue that it fixes. I missed this out yesterday, but the branch name is also slightly incorrect (it should be 'Issue' instead of 'issue'). Have a look at our [development process](https://github.com/TEAMMATES/repo/blob/master/devdocs/process.md).

**Pull request closed without merging**
