### PR TITLE
Update settingUp.md

### PR DESCRIPTION
**Pull request by Siddhant085**
I updated point number 6 and changed "login" to "log in"

### CODE REVIEW

**Comment by damithc** [comment]
@Siddhant085 please complete the orientation task list before attempting to fix issues.

**Comment by damithc** [comment]
Sorry, didn't realize you've done the orientation guide already. Reopening this.

**Comment by Siddhant085** [comment]
How do I know that the update provided by me is all right and that I can move onto the next issue.

**Comment by LowWeiLin** [comment]
@Siddhant085 Do look through the instructions in the docs, the branch name, pull request name and description do not follow the format required.

**Comment by damithc** [comment]
Closing because this is a duplicate

**Pull request closed without merging**
