### PR TITLE
Refine StudentFeedbackSubmissionEdit Java Slice #3573

### PR DESCRIPTION
**Pull request by MrFool**
In here:

1. Code formatting
2. Improved code coverage 
3. Removed TODOs (already done or shouldn't be done / implemented in this PR)
4. Inserted comments for parts as to why code isn't being covered (covered but a higher level entity but can be used as a safety net if higher level entity let it goes through which is not easily producible)
5. Migrated test data to one that is catered for this for finer grain testing

### CODE REVIEW

**Comment by MrFool** [comment]
Ready for review as well, was able to improve code coverage, especially for previously untested methods.

**Comment by damithc** [comment]
How come there is a new test data json file but there isn't much changes to test cases?

**Comment by MrFool** [comment]
Because branches were missed due to there not being responses and questions that catered to their cases, just by adding the questions and responses that would cater to them would make their instructions be run and thus tested.

Or do you mean change the naming of the instructors inside the json file to be more specific and make changes to the test cases respectively?

**Comment by damithc** [comment]
Got it :+1:

**Pull request merged**
