### PR TITLE
AdminActivityLogPageUiTest failing on line 52 #3320

### LINKED ISSUE #3320: AdminActivityLogPageUiTest failing on line 52
<code> assertEquals(expectedPersonInfo,actualPersonInfo); </code>

testfailure

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #3320 
At least now it can pass (most of the time).

### CODE REVIEW

**Comment by damithc** [comment]
@ymoctavia can you review this?

**Comment by ymoctavia** [comment]
@wkurniawan07 

Actually the problem is with the function getPersonInfoOfFirstEntry():

And it should go all the way into the hidden Input which contains the "person filter query"

You can replace it with the following function

```
 public String getPersonInfoOfFirstEntry(){
        
        WebElement table = browser.driver.findElement(By.id("logsTable"));
        WebElement tableRow = table.findElements(By.tagName("tr")).get(1);
        WebElement element = tableRow.findElement(By.tagName("small"));
        WebElement hiddenInput = element.findElement(By.name("filterQuery"));
        return hiddenInput.getAttribute("value");
    }
```

This should solve the problem like this: 
image

And for empty query like 
image

Since the actual query is "person:", which means any log should matches it, this can handled by simply skipping the actual comparing. (This is usually caused by automated actions which do not have a identification string for person query)

**Comment by ymoctavia** [comment]
You can update the above action and modify the function "assertSubstringOfExpectedEquals" to "assertEqualIfQueryStringNotEmpty" to skip empty query comparison.

**Comment by wkurniawan07** [comment]
Right. This works. But actually even if the query is empty, `getPersonInfoOfFirstEntry()` also returns "person:" (as in no skip is needed).

**Comment by ymoctavia** [comment]
@wkurniawan07 

Actually skip is needed when:

Query: "Person:"

Table Entry 1 :      "Person:"
Table Entry 2 :      "Person: alice"
Table Entry 3 :      "Person:"

Since the query "Person:" had no effect to logs page(same to a page refresh),
getPersonInfoOfFirstEntry() will return "person:". 
Then because we are just checking the hidden input's value of second table entry(this is randomly set), there is no guarantee that it will also be an automated action.

**Comment by ymoctavia** [comment]
You can proceed to merge after this :)

**Comment by wkurniawan07** [comment]
I hope it's merge-able now? :p

**Comment by damithc** [comment]
@ymoctavia, if it is ready, go ahead and merge.

**Comment by ymoctavia** [comment]
I will meter this soon.

**Comment by ymoctavia** [comment]
@wkurniawan07 , what is your branch's name? I can't find the remote branch to merge

**Comment by damithc** [comment]
Yang MO, Wilson's branch should be in his own fork, not our main repo.

**Comment by ymoctavia** [comment]
Ok I see... let me check how to merge this

**Pull request merged**
