### PR TITLE
Team members cannot view responses to them if their team name contains html characters #2616

### LINKED ISSUE #2616: Team members cannot view responses to them if their team name contains html characters
If a team name contains html characters, then in studentFeedbackResultsPage, the responses directed at that team will not appear.

### PR DESCRIPTION
**Pull request by bamboo3250**
Fixes #2616 

Now it works properly for characters such as < and >.
100% passed the test suit.

### CODE REVIEW

**Comment by kanghj** [comment]
@damithc, should we fix this temporarily in this way and remove the temporary fix after we have fixed this properly, or should we just directly do the proper fix for this problem?

**Comment by damithc** [comment]
I'm ok with a temporary fix as long as it's not too ugly.

**Comment by bamboo3250** [comment]
There are a lot of bugs with the team name, especially when we use the team name for sending queries. Besides characters < and >, I found that other characters such as " ' and \  in the team name also cause bugs when students send feedback about other teams. However, it is too critical to handle these characters. 

@damithc Can we prevent instructors from using these characters for the team name or not?

**Comment by damithc** [comment]
It is not reasonable to prevent such characters from team names. Usually
students decide team names themselves.

**Comment by kanghj** [comment]
@bamboo3250, sorry, but can you explain more about why the other characters cannot be handled by reversing the sanitization?

**Comment by bamboo3250** [comment]
@kanghj sorry for late reply. Previously, I was afraid that these lines would cause injection like what happens to SQL database if the implementation was just replacing the value of "receiverParam" into the string in the filter. 

screenshot_2

e.g. if the value of receiverParam is "team 1 || receiver == team 2" then the string for query will be "feedbackQuestionId == feedbackQuestionIdParam && __receiver == team 1 || receiver == team 2__ && receiverSection == sectionParam", which is not our desire.

However, after I did a thorough research about JDO and GAE, I think this is not our case thanks to the use of declareParameters() and setFilter(). They can prevent injection like that.

Hence should I fix other characters as well or create a new issue for them?

**Comment by kanghj** [comment]
You can fix the other characters in this issue, since they are part of this issue anyway.

**Comment by bamboo3250** [comment]
@kanghj Okay, thanks. But I need to fix the issue #3204 first in order to fix other characters for this issue. When I tried some special characters, that issue came up and I couldn't even answer the question.

@damithc please allow me to fix the issue #3204 because they are quite related to each other.

**Comment by bamboo3250** [comment]
@kanghj I fixed the other characters. I just found out the existence of the function StringHelper.recoverFromSanitizedText() so there is no need for the extra function.

**Comment by kanghj** [comment]
@bamboo3250, sorry for not realising it earlier, but your solution might be incomplete. This fix does not seem to cover the case when the recipient type is "Giver's team" and only fixes the situation where the recipient is "Other Teams in the course".

**Comment by bamboo3250** [comment]
@kanghj this is another bug that is not related to special characters or sanitization.

screenshot_2

You can see that the condition is "If the recipient is a __TEAM__", which should cover both __Other Teams in the course__ and __Giver's team__ but actually it does not. __Giver's team__ has a different  FeedbackParticipantType, which is __FeedbackParticipantType.OWN_TEAM__ not FeedbackParticipantType.TEAMS. 

Therefore simply adding another OR in that condition will solve the problem but I believe it is not the case of this issue. 

Should we fix it right here?

**Comment by kanghj** [comment]
Looks like you are right and this is a separate bug. We should not fix it here, I will make a new issue for it.

**Comment by kanghj** [comment]
This looks good to me. @LowWeiLin, have a look?

**Comment by LowWeiLin** [comment]
Could you add/modify tests cases for this fix? The tests should fail without the fix.

**Comment by bamboo3250** [comment]
@LowWeiLin should I change data directly in __typicalDataBundle.json__ or somewhere else?

**Comment by LowWeiLin** [comment]
It would be better to not change/add to typicalDataBundle.json as it is used in many places, and is already quite large/slow to load. See if there is any other place?

**Comment by bamboo3250** [comment]
@LowWeiLin I added a test case for this fix. It will fail without the fix.

**Pull request merged**
