### PR TITLE
Inject real accounts to DataBundle via java instead of via json #4647

### LINKED ISSUE #4647: Inject real accounts to DataBundle via java instead of via json
The idea came out in #4586 (quite long ago) but somehow it got left out.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #4647

### CODE REVIEW

**Comment by bamboo3250** [comment]
I see no problem with your code but does this change really make the test run significantly faster than before? I think the trade-off between the optimization and the elegance of the code is worth to be considered here. 
How about we add another `boolean` to `loadDataBundle(String pathToJsonFile)` to check whether we should inject real account into the `jsonString` or not? I think that should be good enough while keeping the code short and simple.

**Comment by wkurniawan07** [comment]
Another benefit that the json method can't replicate is the fact that now the real accounts are situated in the same java file (and better yet, you know which precise attribute use which real account). Would you rather look at the json file just to check which account(s) are used, or just scroll up when you're modifying the test's java file?
Of course, if elegance is _that_ important, I can use the method you suggested, with the above trade-off.

**Comment by damithc** [comment]
I agree the previous way was more concise and looked more elegant. Using a boolean in the java file retain the conciseness to some extent and improves performance. While having the whole shebang in the java file increases the verboseness and duplication, it also gives us more control (e.g. we can add comments) and makes the injection 'harder to miss'. Then again, I think the dev still has to look at the json file because it's hard to figure out what's being replaced by looking at a line like this, right?
`testData.students.get("CCDetailsUiT.alice.tmms@CCDetailsUiT.CS2104").googleId = student1GoogleId;` 
So it's a dilemma.

We can also call a method (instead of a boolean) like this: 
```java
injectAccounts(DataBundle data, String... accountsToInject);
```
That method call shows which accounts are being injected, but the dev has to look at the json file to see where they get injected.
Since there is no clear 'best' option, @wkurniawan07 can make the decision.

**Comment by wkurniawan07** [comment]
I've thought of the alternatives, and still believe this is the best way. Let's see the downsides pointed out:

1. Verboseness in the java file + less conciseness and elegance: these are inherent downsides, I can't do anything with them, but we're getting better performance and more control (which should be more important?) for those.
2. Repetition of the `TestProperties.inst().*ACCOUNT`: I've found a way to suppress it and even introduce more benefits along with it, to be done in another PR.
3. It's hard to figure out what's being replaced by looking at a line like `testData.students.get("CCDetailsUiT.alice.tmms@CCDetailsUiT.CS2104").googleId = student1GoogleId`: not really, that line already contains the information that it's the **googleId** a **student** with **hash key** "CCDetails...", and with the fact that we can comment on why the specific accounts are replaced if needed, this is hardly a downside. On the other hand, the json approach has no way to tell where replacements take place other than a folder-wide search.

@bamboo3250 that's my decision, so I guess it's ready to merge now?

**Comment by bamboo3250** [comment]
Yes, I have no objection. it's good to merge now.

**Pull request merged**
