### PR TITLE
Hardcoded 1-3 Feb 2016 preventing dev green #4701

### LINKED ISSUE #4701: Hardcoded 1-3 Feb 2016 preventing dev green
For the next 3 days we're effectively blocked from dev green because there are test cases with each one of the above date hardcoded (and thus replaced to placeholder).
We can either let 3 days pass (and the issue will just turn to dust) or change the dates :stuck_out_tongue:

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #4701 
Anyone welcome to review, this should be very quick.

### CODE REVIEW

**Comment by thyageshm** [comment]
Everything is good to go.
Could we also change a couple more in `InstructorCommentsPageUiTest.json` on lines 491, 496 and 541 as those dates are coming soon too? 
Hopefully we can fix this problem by March. We probably have to change all the hardcoded dates to something in the past so that this problem does not recur.

**Comment by wkurniawan07** [comment]
Agree on that, but I'm hijacking the issue if I fixed the March dates here.

**Comment by damithc** [comment]
Merge this one and create a new issue for the rest. Can assign to one of the new contributors.

**Comment by thyageshm** [comment]
go ahead and merge!

**Comment by wkurniawan07** [comment]
Found another show-stopping data set, only this time it's worse since it won't be gone unless it's changed. Sorry for including a change without permission, but I really need the fix to be included to get dev green. Will revisit it in a new issue.

**Pull request merged**
