### PR TITLE
Remove trailing tooltipping functions in JavaScript files #3888

### LINKED ISSUE #3888: Remove trailing tooltipping functions in JavaScript files
Related to #3858, I missed out some of the tooltipping functions so I will remove them and check if I also missed out any others in this issue.

### PR DESCRIPTION
**Pull request by junhaoyap**
Fixes #3888, as explained I missed out some of them during one of the recent PRs as my String search wasn't comprehensive enough.

### CODE REVIEW

**Comment by junhaoyap** [comment]
Currently using a more comprehensive string search to remove more trailing ones, apparently there were even more places that it was being activated and used in more varied ways than I imagined when I started on cleaning this up.

**Comment by junhaoyap** [comment]
Will get back to this perhaps tomorrow or the day after, it's still ongoing as of now.

**Comment by junhaoyap** [comment]
Apparently it is done, I was under the misconception that it wasn't but I've just synced it to current master.

**Comment by junhaoyap** [comment]
@ackoroa Do you remember what the setTimeOut at feedbackResponseComments.js line 36 is for?

**Comment by junhaoyap** [comment]
Removing the setTimeOut doesn't seem to break anything, @kanghj can help take a look?

**Comment by ackoroa** [comment]
Eh, I don't think I wrote that haha.

**Comment by junhaoyap** [comment]
Odd, it was traced back to you 10000 commits ago, was it perhaps written before git was used?

**Comment by junhaoyap** [comment]
@damithc do you remember who added all the setTimeOuts in the JavaScript files and what they were for?

**Comment by damithc** [comment]
Not really. `git blame` is our only way to find. But the original developer might not remember why it was like that. This is why we should use comments to document the WHY aspect :-)

**Comment by junhaoyap** [comment]
It traced back to ackoroa but he didn't write it so it might have been written even before git was used? I removed those setTimeOut and the AJAX request became faster, did not break and also no longer screws up the order of the event firing though, should I remove all of the setTimeOut?

**Pull request merged**
