### PR TITLE
Long institute names get cut off in the footer #2993

### LINKED ISSUE #2993: Long institute names get cut off in the footer
image

### PR DESCRIPTION
**Pull request by arvind-kalyan**
Fixes #2993

### CODE REVIEW

**Comment by arvind-kalyan** [comment]
Bootstrap's grid system allows upto 12 columns. Instead of the split we had which was 4-4-4, I changed it to 2-8-2, giving more space for institute name. Please check.

**Comment by LowWeiLin** [comment]
Nice solution! Could you post a screenshot for an institute with max length? It may not just be the length, whitespace may cause the line to split too.

**Comment by arvind-kalyan** [comment]
Thanks! :) Here it is.

**Comment by arvind-kalyan** [comment]
one more screenshot.

**Comment by damithc** [comment]
Good job @arvind-kalyan :+1:

**Comment by LowWeiLin** [comment]
@arvind-kalyan there are many tests failing, most are UI and due to the change. 
For those tests that are not checking the header and footer, you can change verifyHtml to verifyHtmlMainContent, so that the test ignores the footer.
Some tests however(need to look at the test context), may need to check the header/footer and you will have to change the expected html files.

**Comment by arvind-kalyan** [comment]
Oh yes. I have to make the changes in other files accordingly. Will do.

**Comment by arvind-kalyan** [comment]
@damithc  Thank-you sir.
@LowWeiLin Kindly check now.

**Comment by arvind-kalyan** [comment]
@LowWeiLin Hi, Are the changes okay?

**Pull request merged**
