### PR TITLE
instructor session unpublish confirmation dialog: evaluation --> session #3077

### LINKED ISSUE #3077: instructor session unpublish confirmation dialog: evaluation --> session
Since the instructor session publish confirmation dialogs' message has been changed to  evaluation --> session in the issue #2929, the messsage in the unpublish version should also be changed .

### PR DESCRIPTION
**Pull request by wkurniawan07**
fixed #3077 :tada:

### CODE REVIEW

**Comment by kanghj** [comment]
Change the name of the pull request to follow our naming convention (remove the (ref: ) ).

**Comment by wkurniawan07** [comment]
Done!

**Comment by kanghj** [comment]
Remove the brackets too? It should just be <code> instructor session unpublish confirmation dialog: evaluation --> session #3077</code>. Just follow the format given in the (development process)[https://github.com/TEAMMATES/repo/blob/master/devdocs/process.md]

Other than that, looks good to merge

**Comment by wkurniawan07** [comment]
Done! Will do for all subsequent pull requests :+1:

**Comment by wkurniawan07** [comment]
@LowWeiLin @kanghj can I explore other issues now?

**Comment by kanghj** [comment]
@wkurniawan07, yes, you can look for other issues to work on.

**Pull request merged**
