### PR TITLE
 Instructor Unable to comment on all students in a given course #3115

### LINKED ISSUE #3115: Instructor Unable to comment on all students in a given course.
@damithc 
Please Check this image for Error Message. 

error1
error2

### PR DESCRIPTION
**Pull request by kai33**
Fixed #3115 

cause: arbitrary assert_not_null for student email causes this problem.

test cases has been added to stop regression

### CODE REVIEW

**Comment by kai33** [comment]
@franklingu have a look?

**Comment by franklingu** [comment]
okay. I will have a look at this ASAP

**Comment by franklingu** [comment]
I think the changes seem to be fine. You can just merge it in. Sorry for the delay :P

**Comment by franklingu** [comment]
@kai33

**Pull request merged**
