### PR TITLE
Refine FeedbackSessionStats Slice

### PR DESCRIPTION
**Pull request by MrFool**
Refinements include:

Minimal coding convention changes, this wasn't a very big slice so there is really nothing much to refine.

Java Side
. FeedbackSessionStatsPageAction.java

Java Servlet Side
. instructorFeedbackStats.jsp

Testing Side
. FeedbackSessionStatsPageActionTest.java

### CODE REVIEW

**Comment by damithc** [comment]
Test coverage good?

**Comment by MrFool** [comment]
On page action and page data it was 100% when I used Eclemma to test coverage, very small slice this is

**Comment by damithc** [comment]
@kanghj please review and get @MrFool to merge himself. I guess you'll have to add him as a committer first.

**Comment by kanghj** [comment]
Looks good to me

**Pull request merged**
