### PR TITLE
Issue2353

### PR DESCRIPTION
**Pull request by Doomdev**
Fixed the Tool Tip Message in Instructor Student Search .

### CODE REVIEW

**Comment by franklingu** [comment]
Please fix the tests too. and we want better naming for variables.

**Comment by franklingu** [comment]
and the name of pull request is not correct. just open a new one when you are ready. i will just close this

**Comment by Doomdev** [comment]
Thanks for your Guidance ... Got to know allot from you now :+1:  ..Will follow the best practices to name the variable and will change the pull request name to good one .. could you please tell more about - "Please fix the tests too" that you have mentioned above . Thank you for your patience :) appreciated your Support/help .

**Comment by franklingu** [comment]
when you fix a UI related issue, or any non trivial issue, there may be tests that are broken, so we want to make no tests are broken because of the pull request

**Pull request closed without merging**
