### PR TITLE
  Remove Unused branch in Action.java  #3011

### LINKED ISSUE #3011: Remove Unused branch in Action.java
In Action.java, under the method getRegkeyFromRequest(), we have a branch that checks for the legacy regkey parameter name in the url. since we no longer support it, we can remove that check.

### PR DESCRIPTION
**Pull request by vamshi-s**
Fixes #3011

### CODE REVIEW

**Comment by LowWeiLin** [comment]
@vamshi-s The pull request title is in the wrong format (remove the comma), and the description is also wrong. See: https://github.com/TEAMMATES/repo/blob/master/devdocs/process.md

**Comment by LowWeiLin** [comment]
@thyageshm Just checking, are we sure it is okay to remove the branch?

**Comment by damithc** [comment]
If we remove that branch, links sent out prior to that change will not work
anymore. May be allow 12 months to lapse before we remove the branch?

**Comment by thyageshm** [comment]
The thing is the change happened last summer (around July). Anyone who got a join link before that time *should* have used it by now. We could wait for a while longer, but it does not make any difference.

**Comment by damithc** [comment]
You could be right. My concerns is that there can be cases of instructors
signing up in one year and deciding to actually use it in the next year.
Furthermore, some people might not remember the TEAMMATES base URL and
always dig up the join link in the email box when they need to access
TEAMMATES again. What we can do is to put a `log.severe("TEAMMATES accessed
using old join link")` in that branch. If anybody uses that branch, I will
get an email due to the log message. If I never got such an email in the
next couple of months, we can delete the branch.

**Comment by vamshi-s** [comment]
@thyageshm Shall i do those changes as suggested by damith ?

**Comment by LowWeiLin** [comment]
@vamshi-s I have created You can look for harder issues instead, and leave that as a first issue for others.

**Comment by damithc** [comment]
What happened to this code? Looks like somebody merged the incorrect code. I'm getting 'TEAMMATES accessed using old join link' in the log.

**Comment by damithc** [comment]
Seems it was done in PR #3100. I couldn't locate it first because of the incorrect PR name.

**Comment by LowWeiLin** [comment]
The code in the current master branch seems correct.

**Comment by damithc** [comment]
Yes, the code is as intended, but the behavior is not as expected. :-p The
branch that we thought to be 'unused' seems to be used a lot.

**Comment by thyageshm** [comment]
I think I should named the issue properly. It is not that the branch is unused, it is more like the branch is not needed. The check is done almost everytime any page loads. But we do not expect getRequestParamValue(Const.ParamsNames.REGKEY_LEGACY); to return a proper value (ie non-null)

**Comment by damithc** [comment]
So the log.severe should happen if
getRequestParamValue(Const.ParamsNames.REGKEY_LEGACY)
returns a non-null value?

**Comment by thyageshm** [comment]
yup

**Pull request closed without merging**
