### PR TITLE
rename '#frameBodyWrapper' to '#mainContent' in all pages #2059

### LINKED ISSUE #2059: rename '#frameBodyWrapper' to '#mainContent' in all pages

### PR DESCRIPTION
**Pull request by MrFool**
Fixes #2059 

Still not done yet, need to ensure dev green but frameBodyWrapper has been effectively removed from the repo

### CODE REVIEW

**Comment by MrFool** [comment]
Confirmed dev green, can someone self assign and help me look through, thanks!

**Comment by wkurniawan07** [comment]
Nice. I'll review this.

**Comment by wkurniawan07** [comment]
As far as I can see there is only one type of change here and that's changing frameBodyWrapper to mainContent, duplicated 343 times (the 344th one is addition). This can be merged as long as dev green.

**Comment by MrFool** [comment]
Indeed, it was added on one page where there wasn't any and for everywhere else it is changed. Tests are also changed to target mainContent rather than frameBodyWrapper and stuff that used to target frameBodyWrapper in JavaScript were changed to mainContent as well :) It's dev green last I run the test, I'll merge it into master and we can sync it to JSTL-Dev some other time.

**Pull request merged**
