### PR TITLE
Refined InstructorStudentList HTML files with God mode

### PR DESCRIPTION
**Pull request by wkurniawan07**
Pure HTML indentation refinement. Files included:
instructorStudentList.html
instructorStudentListDisplayArchivedCourses.html
instructorStudentListHideArchivedCourses.html
instructorStudentListPageWithPicture.html
instructorStudentListWithHelperView.html

### CODE REVIEW

**Comment by damithc** [comment]
Did you do these manually or using God mode? Shouldn't we keep html files exactly as they have been generated by God mode?

**Comment by wkurniawan07** [comment]
Did one of those huge chunks manually then copy pasting to others, making minor changes here and there as needed. I haven't tried God mode before.

**Comment by MrFool** [comment]
About this, we should fix it via fixing how god mode indents the files rather than manually, because once we activate god mode everything will change again

**Comment by wkurniawan07** [comment]
Then let's put this PR on hold first, I'll see if I can do something with that God mode...

**Comment by kanghj** [comment]
I'll close this pull request for now. You can reopen in future if you want, or make the changes to God mode in another pull request.

**Comment by wkurniawan07** [comment]
Re-opened and renamed the issue as appropriate.

**Pull request merged**
