### PR TITLE
Instructor count includes testing accounts in adminAccountManagementPage #3050

### LINKED ISSUE #3050: Instructor count includes testing accounts in adminAccountManagementPage
Instructor count should not include testing accounts. Also see [link](https://groups.google.com/forum/#!topic/teammates-contributors/kVHhpDI-fAs)

### PR DESCRIPTION
**Pull request by karan173**
Fixes #3050

### CODE REVIEW

**Comment by karan173** [comment]
@kanghj Can you please review this?

**Comment by LowWeiLin** [comment]
@karan173 Have you checked that all tests pass? It is unlikely the page is not tested, but I may be wrong.

**Comment by karan173** [comment]
@LowWeiLin  As you can see from one of my commits, I have modified a test which failed due to the changes.

**Comment by kanghj** [comment]
Looks good then.

**Comment by kanghj** [comment]
@karan173, because you are already at step 6 of [instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true), you can continue to submit pull requests to fix issues, but we no longer promise to review or merge these pull requests. Also, try to fix tougher issues from now on.

**Comment by karan173** [comment]
@kanghj Yeah will look at some tougher issues from now on. Thanks!

**Pull request merged**
