### PR TITLE
Refine InstructorFeedbackRemindParticularStudentsAction

### PR DESCRIPTION
**Pull request by taniach**

### CODE REVIEW

**Comment by kanghj** [comment]
Remember to also look at the logic and db level code, as well as jsp files

**Comment by taniach** [comment]
Shall I refactor the logic and db level code too or just read it?

**Comment by kanghj** [comment]
Yup, you should refactor them if you can.

**Comment by damithc** [comment]
But ok (recommended) to do as separate PRs.

**Pull request merged**
