### PR TITLE
AdminHomePageUiTest fails frequently at line 162 #2961

### PR DESCRIPTION
**Pull request by franklingu**
for #2961

### CODE REVIEW

**Comment by franklingu** [comment]
the file changes are too significant. needs refinement

**Comment by franklingu** [comment]
in fact, some changes are wrong

**Comment by franklingu** [comment]
strange. I changed those instructorHomePageHtmls manually...

**Comment by franklingu** [comment]
for some reason, the UI html changes are huge and number of lines do not match. @LowWeiLin , is the testing server still running? or you can just run this for reviewing...

**Comment by damithc** [comment]
If you can't go through the changed html files manually and verify they are
correct, then there is not much value even if the test cases are passing.
God mode changes html files to match the actual output, so they should pass
anyway. But that doesn't mean the behaviour is correct.

**Comment by franklingu** [comment]
"strange. I changed those instructorHomePageHtmls manually..." you can see the comment above

**Comment by LowWeiLin** [comment]
@franklingu InstructorFeedbackPageUiTest is the only one failing in the branch. Failing at line 118

**Comment by franklingu** [comment]
@LowWeiLin thanks a lot. but probably I will see if I can fix homepage htmls with huge changes also.

**Comment by damithc** [comment]
Is this branch behind master? The changes shown in the pull request don't
match the issue.

**Comment by LowWeiLin** [comment]
The branch is ahead. The current master is merged in.

**Comment by damithc** [comment]
In that case, we need to know why there are so many unrelated changes in
the pull request if the changes were done manually. Is it because of 'tab
vs spaces' issue? Can we revert the unrelated changes?

**Comment by franklingu** [comment]
most likely related to indentation issue. However, seems some stuff is
missing too(- is more than +) although not obvious to me the missing lines.




Gu Junchao
Major in Computer Engineering, National University of Singapore
Primary Email: *franklingujunchao@gmail.com <franklingujunchao@gmail.com>*
NUS Email: *A0105750@nus.edu.sg <A0105750@nus.edu.sg>*

**Comment by damithc** [comment]
I don't think these changes were manually done. Just revert everything and
manually change where things are supposed to change. It is just a change in
one HTML attribute, is it not?

**Comment by franklingu** [comment]
I did change manually 7 htmls for instructorHomePage. but I am not sure why
this happened. even if I used god mode, it should not give me so many
unrelated changes--in the case of adminHomePage and
feedbackresults/feedback I used god mode. I will do another round of manual
change in this case--yes just one html attributes but occurred several
times in one page.




Gu Junchao
Major in Computer Engineering, National University of Singapore
Primary Email: *franklingujunchao@gmail.com <franklingujunchao@gmail.com>*
NUS Email: *A0105750@nus.edu.sg <A0105750@nus.edu.sg>*

**Comment by damithc** [comment]
This issue shouldn't have taken this much time from this many people :-)

**Comment by franklingu** [comment]
I have no idea why that happened although I changed manually before. one reason possible is that after manual change last time(homePageUiTest ended), I ran adminHomePageUiTest under godmode once. but it seems unlikely cause homePageTest was done at that time(master was merged in already).

**Comment by franklingu** [comment]
seems those files were changed in dec 2014 and after that, this is the only commit to change them. normally even if godmode is used, huge changes should not incur though(like in the case of adminHomePageUiTest pages).

**Comment by damithc** [comment]
Is this done? If yes, go ahead and merge.

**Comment by franklingu** [comment]
fixes #2961

**Pull request merged**
