### PR TITLE
Ensure JSTL green #3762

### PR DESCRIPTION
**Pull request by wkurniawan07**

### CODE REVIEW

**Comment by MrFool** [comment]
looks good so far, just need to fix the modal div in the many pages

**Comment by kanghj** [comment]
Since you have a partial fix for the feedbacks page and you're not working on this now, I'll just fix the modal divs on this branch right now

**Comment by MrFool** [comment]
Is this all passing except for instructor search? If yes I can take a look at it.

**Comment by MrFool** [comment]
Running the tests and going for lunch, will come back and finish eyeballing

**Comment by MrFool** [comment]
Confirmed dev green and all changes look fine ;)

**Pull request merged**
