### PR TITLE
Show a 'You are submitting as ...." message when an unregistered student submit responses #3291

### LINKED ISSUE #3291: Show a 'You are submitting as ...." message when an unregistered student submit responses
Currently, the submission page does not show the identity of the submitter. If we show a 'You are submitting as XYZ' message on top, it reduces the chance of person ABC submitting as person XYZ because XYZ forwarded the unique link to ABC (they are not supposed to do that, but some still do).

image

### PR DESCRIPTION
**Pull request by acruis**
Fixes #3291 

In addition to the "Submit Feedback" page, other pages that an unregistered student can see (Submit Feedback Question & View Feedback Results) are also updated.

* **Submit Feedback**
submit feedback
* **Submit Feedback Question**
submit question
* **View Feedback Results**
view results

### CODE REVIEW

**Comment by kanghj** [comment]
Looks good to me

**Comment by damithc** [comment]
On second thoughts, may be use 'responses' instead of 'feedback' and 'feedback results'? Some sessions may not be strictly feedback sessions. What do you guys think? 
Bolding the name is good, but I'm not sure it that's enough to attract the attention of the user. Anything more we can do?

**Comment by kanghj** [comment]
Yes, 'responses' would be more consistent with the StudentHomePage, where the button says 'View Responses'. 

I think there are other status messages right now that use 'feedback' instead of 'responses', such as 'You have not received any new feedback but you may review your own submissions below.'. If we use 'responses' instead of 'feedback' here, we should change the other status messages as well, in another issue.

**Comment by acruis** [comment]
Yep, I also think 'responses' is better.

To attract the user's name, if we're going for impact then...

How about this?
image

Or even this:
image

The latter might be a bit too conspicuous though. What do you think?

**Comment by damithc** [comment]
How about we keep the original format but use a different color for the
name? Contrast attract attention. Even if the font size is big, it doesn't
attract attention if the rest of the text is just as big, so having the
name in the main heading doesn't help much.

**Comment by acruis** [comment]
Ah, so something like this then.
image
We can also make the name bigger.
image

**Comment by damithc** [comment]
Nice. We can go with the 2nd one.

**Comment by acruis** [comment]
Alright :) I'll implement the second one then.

**Comment by acruis** [comment]
I'm done with this. Do review if you have time.

**Comment by kanghj** [comment]
Looks good

**Pull request merged**
