### PR TITLE
Error when adding email to task queue: log more info #4290

### LINKED ISSUE #4290: Error when adding email to task queue: log more info
I get this in error logs `teammates.logic.core.Emails addEmailToTaskQueue: Error when adding email to task queue`
Is it possible to log more information when this error happens?

### PR DESCRIPTION
**Pull request by junhaoyap**
Fixes #4290

### CODE REVIEW

**Comment by junhaoyap** [comment]
@damithc is the above information enough? I added email sender, receiver, reply to address and also the subject.

**Comment by damithc** [comment]
Should be enough.

**Comment by junhaoyap** [comment]
@kanghj take a quick look at the implementation before I merge? :)

**Comment by kanghj** [comment]
Ok, looks good :)

**Comment by junhaoyap** [comment]
Thanks!!!

**Pull request merged**
