### PR TITLE
Add courseId in the confirmation dialog when instructor deletes a student #3089

### LINKED ISSUE #3089: Instructor: Add a courseId in the message shown in the confirmation dialog of 'delete student' button
In instructorCourseDetails.js, the message in the confirmation dialog of 'delete student' button is with the format:

```
"Are you sure you want to remove " + studentName + " from " + "the course?"
```
The message should be formatted in the same way as the confirmation dialog in the other js files (instructorSearch.js and instructorStudentList.js)

```
"Are you sure you want to remove " + studentName + " from " + "the course " + courseId + "?"

### PR DESCRIPTION
**Pull request by yuqingw**
Fixes #3089

### CODE REVIEW

**Comment by kanghj** [comment]
For this issue, other than adding the parameter to the function, the call to toggleDeleteStudentConfirmation in instructorCourseDetails.jsp needs to be changed to include the additional parameter. After modifying the jsp file, the test html files checked in InstructorCourseDetailsPageUiTest should be updated too.

**Comment by yuqingw** [comment]
@kanghj Ok got it, I'll work on updating the jsp and test pages

**Comment by yuqingw** [comment]
@kanghj while looking at the test pages, I noticed "InstructorCourseDetailsPage.java" in src/test/java/teammates/test/pageobjects would also need modification in method "InstructorCourseDetailsPage clickDeleteAndCancel(String studentName)" and that would mean replacing "getStudentRowId(studentName)" into "getStudentRowId(courseId, studentName)" like what is being done in "src/test/java/teammates/test/pageobjects/InstructorStudentListPage.java". Should I modify this as well?

**Comment by kanghj** [comment]
@yuqingw, on InstructorCourseDetails, I believe there is only the details of one course displayed, so there is no need to add the additional parameter courseId in clickDeleteAndCancel. The student name should be sufficient for identifying which row is to be clicked. This is different in InstructorStudentList, where students from multiple courses can be displayed. 

I might be wrong, but I don't think this issue will require changes to the logic inside tests, just the test .html pages for comparisons.

**Comment by yuqingw** [comment]
@kanghj thanks for all the help, let me know if this is fine!

**Comment by kanghj** [comment]
Good work figuring out which files required modifications. Some of the changes are still insufficient to get the test to pass though, on InstructorCourseDetailsWithoutSections.html, line 261 and 309 still has a call to toggleDeleteStudentConfirmation without the courseid.

**Comment by yuqingw** [comment]
@kanghj sorry for the carelessness! Updated it already.

**Comment by kanghj** [comment]
Ok, this looks good. Good work.

**Pull request merged**
