### PR TITLE
index.html: update entry count placeholder to a six digit number #2766 

### LINKED ISSUE #2766: index.html: update entry count placeholder to a six digit number
Currently, it shows 36,000 (before it dynamically updates to the actual count). Change it to 1,000,000 so that it is the same length as the final number.

### PR DESCRIPTION
**Pull request by JosephineKwa**
Fixes #2766

### CODE REVIEW

**Comment by damithc** [comment]
@kanghj can you be the reviewer for this PR?

**Comment by kanghj** [comment]
Looks good to merge, although the commit message format looks similar to the format used when we merge into master and this might be misleading in future.

**Comment by JosephineKwa** [comment]
Do I omit the [Issue Number] when committing?

**Comment by damithc** [comment]
@JosephineKwa I updated the process.md just now to clarify it :-)
@kanghj Yes, go ahead.

**Pull request merged**
