### PR TITLE
Add 'moderate' link in all results view #3019

### LINKED ISSUE #3019: Add 'moderate' link in all results view
Presently, the instructor can see the link to moderate a student's answers only when grouping by either Giver > Question > Recipient or Giver > Recipient > Question. The instructor should be able to get to the moderations page from all results view.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #3019

### CODE REVIEW

**Comment by wkurniawan07** [comment]
The implementation can be seen in the issue thread itself #3019.
And this is not ready to merge yet because it's one test shy of dev green: InstructorFeedbackResultsPageUiTest. If anything, it's because the number of pages that I need to change is... well...  nightmarish :scream:
Do review my codes and my implementation. Meanwhile, allow me up to one week to actually change all those affected pages.

**Comment by wkurniawan07** [comment]
Make it 3 days. I found a really quick workaround to change the affected pages.

**Comment by wkurniawan07** [comment]
I finished changing all the test pages much sooner than expected as I found a really quick workaround (took me less than 5 mins per page). Now I'm working at making tests for the moderate responses links.

**Comment by damithc** [comment]
What's the workaround? :-)

**Comment by wkurniawan07** [comment]
When I did the first page by menial labor (i.e copy and paste every single new "Moderate Response" button), I noticed that the spots that I need to place the button has the same formatting, which is
```
</td>
(a certain number of white spaces/tabs) </tr>
```
There were variations on that certain number of white spaces/tabs, but I remember that in total there are no more than 3 such variations, which makes life really much better. With this, I used find-and-replace and slotted in the button to every single place where they are needed.
The bigger problem then came: every single button is exactly the same except for the target e-mail (as part of HTML field "value"). However, my belief that HTML comparison is only relevant for the presence and the styling of each HTML element and some attributes such as "value" are actually irrelevant and can be skipped. With this in mind, I set the values in the expected pages to {*}, i.e they will accept any e-mail address. It worked awesomely.
With the above techniques, the work I feared before became a mere find-and-replace work, less than 5 mins per page :smile:

**Comment by damithc** [comment]
Eclipse also supports regular expression find and replace. Hard to master,
but once mastered, it can be a big help in cases like this.

**Comment by wkurniawan07** [comment]
This is as far as I can go.
Not that I don't know how to test the buttons in RQG/RGQ view, but there is no good way for me to actually locate and capture the "Moderate Response(s)" button.
In Question view, each response table falls under a fixed id (something like "response-for-question-number-7") and I can locate them in a deterministic way, thus I can make test cases for it.
This is not true for all other views (I believe this is why even GQR/GRQ have no such test), where the response table can fall under things like "panel-heading-7" or "panel-heading-8" where 7 or 8 are in no way related to the question number (or giver/recipient, for that matter).
I can try to fix this, but I believe this should actually be a new issue.

**Comment by imouto1994** [comment]
The feature is ok to merge. However, we can have another issue allowing the instructor to scroll directly to the edited question when he clicks on the 'Moderate' button for one specific response

**Pull request merged**
