### PR TITLE
Migrate legacy data for isArchived variable #2884

### LINKED ISSUE #2884: Migrate legacy data for isArchived variable
Write a script to set the isArchived variable for instructors to be true if it is null, and if the course's isArchived variable is true. Set to false otherwise.

This is so that we can stop supporting legacy data where isArchived is set in the course instead of in each instructor.

### PR DESCRIPTION
**Pull request by kanghj**
Fixes #2884 

When the isArchived attribute was first added to Instructor, one of the methods wasn't updated to modify the isArchived attribute. This pull request fixes that too.

### CODE REVIEW

**Comment by damithc** [comment]
Avoid doing multiple things in the same branch. Now we cannot reverse the bug fix without losing the migration script :-p

**Comment by ymoctavia** [comment]
Professor @damithc, 
@kanghj 

Just a gentle reminder, this may affect admin in masquerading as instructor. Admin will not see any active courses in masquerading mode.

Here are screenshots:

image

**Comment by ymoctavia** [comment]
Opps.. I did not notice the #2850, Please ignore the above message :)

**Comment by damithc** [comment]
The two may be related, but two different issues.

**Pull request merged**
