### PR TITLE
Add banner support #2831

### LINKED ISSUE #2831: Add banner support
As per title

### PR DESCRIPTION
**Pull request by LowWeiLin**
Fixes #2831

Left the default app.student.bannerurl as empty in build.template.properties
Can use test-student-banner.html to test this feature.

Banner added to student submission page

### CODE REVIEW

**Comment by damithc** [comment]
Shall we name this feature MoD (Message of the Day)? If yes, rename stuff accordingly. Go ahead and merge, and post a screenshot.

**Comment by LowWeiLin** [comment]
Sure, will rename the stuff.
Screenshot:
image

**Comment by damithc** [comment]
May be use some sort of panel/border with a title "TEAMMATES Message of the
Day"? Don't use the same blue we use for the rest of the page though.

**Comment by LowWeiLin** [comment]
The entire blue background is part of the separate html. There is no visible styling done, except to restrict the width and have some margin.

**Comment by damithc** [comment]
Can the jsp hold a border? That way, all MoD's will have the same border
around it without having to repeat the style in each html fragment.

**Comment by LowWeiLin** [comment]
Sure, will add in a border.

**Comment by LowWeiLin** [comment]
image

@damithc does this look okay? I added in a close button as suggested by @kanghj

**Comment by LowWeiLin** [comment]
@damithc can i merge this?

**Comment by damithc** [comment]
Sure.

**Pull request merged**
