### PR TITLE
Give FeedbackResponseComment add ajax action its own jsp #3755

### LINKED ISSUE #3755: Give FeedbackResponseComment add ajax action its own jsp
Similar to #3716 and #3718.
frcajax
To have a better look, check `feedbackResponseComments.js`.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #3755 
Tested manually and with IFResultsPageUiTest (as far as I know this is the only UI test that touches FRCs), everything looks well.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@JosephineKwa do you have time to review this now? :smiley:

**Comment by JosephineKwa** [comment]
Yup, sorry bout the delay, will review it now

**Comment by wkurniawan07** [comment]
No worries. Do learn the code, though, I think you're the one who will migrate this to JSTL :stuck_out_tongue: 
That said, just ping me if you need clarification for any part.

**Comment by JosephineKwa** [comment]
Regarding the code style, it looks good to me :+1: 
I believe InstructorComments also allows you to add FRCs, I've tested it (manually) too, and it seems to work fine :) Perhaps it would be good to add a test for it on InstructorCommentsPageUi test too

**Comment by wkurniawan07** [comment]
Oh, that. Let me explain.
InstructorComments does allow you to add FRCs, but they're not loaded to the page in the same way as the ones in InstructorFeedbackResults. If you check the algorithm in `feedbackResponseComment.js`, line 39, you'll find that after the comment is added, the session's panel heading is re-clicked, which will trigger the `InstructorFeedbackResponseCommentsLoadAction`. This is independent of the changes that I made.

**Comment by wkurniawan07** [comment]
You may think that such method is expensive because for every FRC added the page needs to make ajax request to load the panel, going through unnecessary operations which includes database queries. I think so too. It definitely needs to be improved. But not in this PR.

**Comment by JosephineKwa** [comment]
I see, in that case, it looks good to merge.

**Comment by JosephineKwa** [comment]
I guess we could open a new issue regarding the unnecessary re-querying of the database and work on it once this is done :)

**Comment by wkurniawan07** [comment]
@JosephineKwa issue opened. Are you adventurous enough to take it or any other of the comments issues that I just opened? :stuck_out_tongue:

**Comment by JosephineKwa** [comment]
Got it! The slight differences in the comments between the different pages has been bugging me for awhile now :/ I'll try #3838 out and see how it goes

**Pull request merged**
