### PR TITLE
Tidy up link generators in *PageData #3811

### LINKED ISSUE #3811: Tidy up link generators in *PageData
I was thinking of migrating the link generators somewhere more appropriate, but it turns out the current ones need some serious tidying up. Going to tidy it up first before migrating, if migration is needed that is.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #3811 
The word 'Page' is omitted from the method names to minimize the changes.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@junhaoyap if you don't mind

**Comment by junhaoyap** [comment]
Sure, didn't notice this but I'll look at it

**Comment by junhaoyap** [comment]
From what I see, the PR's main idea is to minimize code repetition by moving some common methods from respective *PageData to PageData.java yes?

The changes look ok but there are conflicts now, maybe can deconflict and ping me again, I can then look through one more time before setting it to to merge.

**Comment by wkurniawan07** [comment]
Pretty much that's the purpose. I've deconflicted it.

**Comment by junhaoyap** [comment]
:+1:

**Pull request merged**
