### PR TITLE
studentEvalResults: the link to the description of the point calculation points to the now defunct spec.html #1554

### LINKED ISSUE #1554: studentEvalResults: the link to the description of the point calculation points to the now defunct spec.html
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on January 25, 2014 19:38:02_

We might have to put that documentation in a separate page.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1555_

### PR DESCRIPTION
**Pull request by ngzhian**
Fixes #1554 
The old issue description referenced `studentEvalResults.jsp`, but I think that has been refactored into smaller bits now. I tracked down the old link to to this html `feedbackQuestionContribResultStatsStudentViewAdditionalInfo.html` and updated the link there to the google docs one. Let me know if I got it wrong, thanks!

### CODE REVIEW

**Comment by ngzhian** [comment]
I did another search, found the same link in other places as well:

`instructorHelp.html`
https://github.com/TEAMMATES/repo/blob/master/src/main/webapp/instructorHelp.html#L577
https://github.com/TEAMMATES/repo/blob/master/src/main/webapp/instructorHelp.html#L588

`newlyJoinedInstructorStudentFeedbackResultsPage.html`
https://github.com/TEAMMATES/repo/blob/master/src/test/resources/pages/newlyJoinedInstructorStudentFeedbackResultsPage.html#L176

`studentFeedbackResultsPageCONTRIB.html`
https://github.com/TEAMMATES/repo/blob/master/src/test/resources/pages/studentFeedbackResultsPageCONTRIB.html#L176

should all these be updated as well?

**Comment by wkurniawan07** [comment]
Hi @ngzhian, while we appreciate your contribution, please note that you should not do more than one `forFirstTimers` issue for these reasons:
1. After doing one such issue, you're no longer a first timer.
2. We need these issues for incoming new developers like yourself.
You can choose any one of the PRs you've opened so far for us to review and close the other two. Thanks for contributing to TEAMMATES! :)

p.s if you choose to keep this one, do note that the PR title is wrong.

**Comment by ngzhian** [comment]
@wkurniawan07 thanks for the feedback, strangely it didn't occur to me that I would only be a first timer once! :P anyway I've updated the PR name to follow the process (named after the issue).

**Comment by ngzhian** [comment]
@wkurniawan07 my other PR for `forFirstTimer` issues are:

https://github.com/TEAMMATES/repo/pull/3970
https://github.com/TEAMMATES/repo/pull/3969

feel free to close any of those task. I feel like this is the most important one because we don't want them to go to an old link that (possibly) has wrong info. The core team knows more about the importance so I'll have to leave the closing up to you (sorry).
Nonetheless, I'll be looking around the repo to find more low priority task for first timers :)

**Comment by junhaoyap** [comment]
Alternatively, you can look for forContributors tasks, they might take more time as you'd have to touch more files but it'll help you learn the code base much better than forFirstTimer issues can! Appreciate your contributions and interest :)

**Comment by wkurniawan07** [comment]
Indeed, this is the most important task out of all three that you've worked on. Yes please do change those as well.

**Comment by ngzhian** [comment]
@wkurniawan07 changed all those as well.
Side note, should we control this URL via our own url?
E.g. have /pointsCalculation redirect to the this google docs url

**Comment by wkurniawan07** [comment]
Feel free to open that as a new issue if you wish so, but as far as this issue is concerned, nothing else needs to be done :)

**Pull request merged**
