### PR TITLE
Update the link to HTML style guide #3166

### LINKED ISSUE #3166: Update the link to HTML style guide
This is the outdated link to the HTML guide : 
https://github.com/TEAMMATES/repo/blob/master/src/main/webapp/dev/htmlstyleguide.html

It needs updating in README.md and any other document where this link is given.

### PR DESCRIPTION
**Pull request by EgbeEugene**
Fixes #3166

### CODE REVIEW

**Comment by damithc** [comment]
@EgbeEugene always go through the changes in your pull request to make sure it contains only what you intended it to contain. We are looking for contributors who are able to pay attention to details like that.

**Comment by EgbeEugene** [comment]
thanks for the correction i will do my possible best

**Comment by EgbeEugene** [comment]
please will i have to do the pull request again?

**Comment by LowWeiLin** [comment]
No need to create a new pull request. You can continue committing to the same branch, and this pull request will be updated.
You can look under the files changed tab to see what files have changed, and remove the unrelated changes.

**Comment by kanghj** [comment]
This issue has fixed by #3185, which has been set to toMerge.

**Pull request closed without merging**
