### PR TITLE
 Remove showMessage #4625 

### LINKED ISSUE #4625: Remove showMessage
No longer used. The removal involves:

1. `showMessage.jsp`
2. `showMessage.html`
3. `SHOW_MESSAGE` constant in `Const.ViewURIs`
4. A few lines referring to this in `AllAccessControlUiTests`

### PR DESCRIPTION
**Pull request by tarun14110**
Fixes #4625

### CODE REVIEW

**Comment by tarun14110** [comment]
Removed
    1. showMessage.jsp
    2. showMessage.html
    3. SHOW_MESSAGE constant in Const.java
    4. lines referring to this in AllAccessControlUiTests.java

**Comment by yj-soh** [comment]
Hello @tarun14110, when creating PRs, please do follow the format specified in [process.md](https://github.com/TEAMMATES/repo/blob/master/devdocs/process.md#fixing-issues).
In particular, do read the section beginning with "Create a pull request (PR)."

In addition, when committing, please mention what was done in that commit instead of pasting in the issue or branch name.

**Comment by tarun14110** [comment]
@yj-soh I will be more careful from next time.

**Comment by thyageshm** [comment]
@wkurniawan07, review this?

**Comment by wkurniawan07** [comment]
Thanks for your contribution @tarun14110 :+1:

**Pull request merged**
