### PR TITLE
Upgrade to SDK 1.9.27 #4499

### LINKED ISSUE #4499: Upgrade to SDK 1.9.27
As of now we are 23 SDKs (1.5 years of development time) behind the staging/live server, so I think it's about time we get ourselves updated.
I managed to upgrade without any problem, although with a (small) price to pay: the local database is not compatible and must be replaced with a new one, i.e whatever TEAMMATES data that exists in my PC are wiped out (I made a copy, so I can switch between SDKs freely, but the data between instances of different SDKs are not transferrable).
If agreed, I will come up with the upgrading guide as well, like what I did with Selenium back then.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #4499 
Upgrading guide will be out soon. Tentatively, this will be merged earliest next week (end of next milestone) so everyone can have an ample time to upgrade.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
[Here](https://gist.github.com/wkurniawan07/02a66937e52c1b206123) is the upgrading guide!

**Comment by damithc** [comment]
Let's do this right after the current milestone.

**Comment by thyageshm** [comment]
Ok! I am checking the migration now. If all works out, we can wait till AFTER the current milestone to merge

**Comment by thyageshm** [comment]
looks good. I will update the status right after this milestone

**Comment by wkurniawan07** [comment]
I'm ready to merge it anytime :p

**Comment by thyageshm** [comment]
@damithc sir, I guess we can merge now?

**Comment by damithc** [comment]
Sure

**Comment by wkurniawan07** [comment]
Dr @damithc we need the library to be updated with the new jars (which ones need replacement can be found in the upgrading guide). Until then I can't merge yet.

**Comment by damithc** [comment]
I've upgraded and uploaded the zip file.

**Comment by wkurniawan07** [comment]
We're good to go. Also:
image
I haven't had this few failures for a while (usually a lot are killed by timeouts), quite evidently a lot of optimization has been done after 23 SDKs. We're getting very close to straight dev green once again!

**Pull request merged**
