### PR TITLE
Remove html comparisons from AdminActivityLog #4364

### PR DESCRIPTION
**Pull request by bamboo3250**

### CODE REVIEW

**Comment by taniach** [comment]
Good to merge

**Comment by kanghj** [comment]
Merge this soon?

**Comment by bamboo3250** [comment]
should I wait for #4397 get fixed first or just merge right away? That stopped me from getting dev green.

**Comment by kanghj** [comment]
I think you can merge first

**Comment by kanghj** [comment]
Fixes #4364

**Pull request merged**
