### PR TITLE
Instructor edit feedback session: Rephrase "Who is giving feedback to whom?" #3297

### LINKED ISSUE #3297: Instructor edit feedback session: Rephrase "Who is giving feedback to whom?"
These two phrases don't match. Rephrase the first one to match the second one?
image

### PR DESCRIPTION
**Pull request by tangzijian**
Fixes #3297

### CODE REVIEW

**Comment by damithc** [comment]
May be 'Who is giving feedback about whom?' @LowWeiLin who or whom?

**Comment by LowWeiLin** [comment]
'Who is giving feedback about whom' is correct.

**Comment by tangzijian** [comment]
Sorry. I misunderstand the issue. Then I change it to 'Who is giving feedback about whom'?

**Comment by LowWeiLin** [comment]
Yes

**Comment by tangzijian** [comment]
Done.

**Pull request merged**
