### PR TITLE
instructor session copy: the session name is more restrictive than necessary #2932

### LINKED ISSUE #2932: instructor session copy: the session name is more restrictive than necessary
When creating a session, the session name can have symbols such as '('. But when copying, such symbols are not allowed.

### PR DESCRIPTION
**Pull request by kanghj**
Fixes #2932

### CODE REVIEW

**Comment by LowWeiLin** [comment]
Looks good, but do we need the client side validation? This is inconsistent with other actions elsewhere (add/copy) where validation is done server side.

**Comment by damithc** [comment]
I prefer to use server-side validation only. Although it affects usability, it will avoid this kind of regressions in the future.

**Comment by kanghj** [comment]
I have removed client-side validation for copying feedback sessions.

**Comment by damithc** [comment]
How come this one is not merged yet?

**Comment by kanghj** [comment]
There are some merge conflicts regarding the dropdown for sending reminders to students that I wasn't sure of the correct expected html, so I was waiting for #2923 to be resolved. I will merge this in first then, and replace the parts of the expected html with whatever is in the output now.

**Pull request merged**
