### PR TITLE
InstructorFeedbackResultsPageUiTest fails and freezes at line 281 #4221

### LINKED ISSUE #4221: InstructorFeedbackResultsPageUiTest fails and freezes at line 281
```
resultsPage.verifyHtmlMainContent("/instructorFeedbackResultsSortSecondSessionQuestion.html");
```
We have two random variants of the page that can be returned during test, the one that makes it pass:
visibility_pass
and the one that fails it:
visibility_fail
Notice the two swapped names. What makes this random failure so annoying is that each time it fails, the test will just freeze (the test file has 296 wildcards in it). Killing the browser does _not_ immediately stop it. I once took the liberty to wait for it to finish, it took 25 minutes. Whut.
I am inclined to believe that this is because of #4151, because it didn't happen before and it's likely due to the names of the students in the team with no responses not sorted in any particular order (if this is true, funny that it's only those two names that are randomized, though).

### PR DESCRIPTION
**Pull request by JosephineKwa**
Fixes #4221

### CODE REVIEW

**Comment by JosephineKwa** [comment]
Changed the `Set` used to store student emails from `HashSet` to `TreeSet` so that the emails would be in a fixed order, thus students would be in a fixed order.

**Comment by JosephineKwa** [comment]
@wkurniawan07 for your review

**Comment by wkurniawan07** [comment]
Looks good :+1: just ensure dev green though, I have a feeling it'll affect something else other than that test file. (I could be wrong)

**Comment by JosephineKwa** [comment]
I thought it might affect other tests too, I managed to get dev green though (haven't merged in the latest master).

**Pull request merged**
