### PR TITLE
Sort buttons does not render properly on all screen sizes on Instructor Home #3907

### LINKED ISSUE #3907: Sort buttons does not render properly on all screen sizes on Instructor Home
Does not render properly on some screen sizes, it does on mine but not on @kanghj

### LINKED ISSUE #4096: instructorHome: sort buttons overflow
image

### PR DESCRIPTION
**Pull request by bamboo3250**
Fix #3907 (you can find the screenshot of this fix here)
Fix #4096

@kanghj could you pull this PR and try on your laptop?

### CODE REVIEW

**Comment by damithc** [comment]
Screenshot looks fine

**Comment by kanghj** [comment]
Looks good to merge. Take note of the new branch name convention.

**Comment by bamboo3250** [comment]
Can it be `3907-instructor-home-sort-buttons`?

**Comment by kanghj** [comment]
Actually I think you can just merge this as it is now, just take note for your future pull requests.

**Pull request merged**
