### PR TITLE
mashup.jsp: make session instructions multi-line #1498

### LINKED ISSUE #1498: mashup.jsp: make session instructions multi-line
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on January 13, 2014 18:33:38_

Otherwise, we can't see how the UI show multi-line instructions

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1499_

### PR DESCRIPTION
**Pull request by MrFool**
Fixes #1498, in addition improved code consistency according to Teammates guidelines.

### CODE REVIEW

**Comment by kanghj** [comment]
Can you post a screenshot of your changes?

**Comment by damithc** [comment]
I was expecting a change to the data. i.e. insert some line breaks in instructions of one of the sessions.

**Comment by MrFool** [comment]
Ok, does that mean this part or am I mistaken?

screen shot 2015-04-02 at 1 22 14 am

If yes, sure I can insert line breaks instead.

**Comment by damithc** [comment]
No, this issue refers to instructions entered by instructors when they set up a session. e.g. 'please answer all questions' Some instructors might have line breaks in their instructions.

**Comment by MrFool** [comment]
Ok, I get what you mean now

**Comment by MrFool** [comment]
Updated,

screen shot 2015-04-02 at 1 53 08 pm
screen shot 2015-04-02 at 1 53 15 pm

One with text overflowing to the next line, and one showing how it looks like with <br>.

**Comment by MrFool** [comment]
Updated with +2 commit to improve JavaScript consistency according to Google JavaScript guidelines + best practices

**Comment by MrFool** [comment]
Just did a full test run, dev green with latest commit

**Comment by kanghj** [comment]
I think that using javascript to modify the appearance of the pages shown in mashup.jsp may not be the right way to do this issue. Could you instead modify MashupPageUiTest.json? Anyway, there should be other pages, other than those 2 pages modified, that contains session instructions.

**Comment by MrFool** [comment]
Yupp, there are others, but was the idea to have all of them be multi line or have some be multi line and some not so that we can have a mixture of "looks"

**Comment by damithc** [comment]
Yes, modifying the json file seems like the way to go.
Yes, a mixture is fine.

**Comment by MrFool** [comment]
Ok, now -

screen shot 2015-04-03 at 2 25 17 pm
screen shot 2015-04-03 at 2 23 49 pm

On mashup, only 1 eval and 1 feedback session is used so I've edited both to be multi line (no more single lines), screenshot shows the <br/> tags and that's good (html sanitized) but don't worry I've removed them from the final JSON that is still in the mashup file so final result -

Both are multi line but note that they look slightly different.

**Comment by MrFool** [comment]
Ok so for a quick explanation of the changes -

1. JSON changed to reflect multiline - pertaining mainly to the issue itself

2. Re-ordered css / JavaScript / reficon / title to make them more orderly and removed deprecated stuff such as language="JavaScript"

3. Removed html on load event handlers and moved them into JavaScript via jQuery

4. Inline JavaScript now protected by a self inducing function to prevent global namespace pollution

5. Indentations of inline JavaScript fixed so that developers can easily see which portion have JSP logic instead of all having the same indentation

**Pull request merged**
