### PR TITLE
Refine StudentFeedbackResults Jsp Slice #3581

### PR DESCRIPTION
**Pull request by MrFool**
Done with formatting, just need to check whether anything broke - not likely but sitll have to check

### CODE REVIEW

**Comment by MrFool** [comment]
Ready to be reviewed

**Comment by MrFool** [comment]
Conflicts due to recent god mode regeneration, will deconflict the HTML changes before merging within the next few days

**Comment by wkurniawan07** [comment]
Or, you know, you can just regenerate your HTML files with God mode also :p

**Comment by MrFool** [comment]
That's the plan, during the weekends :p

**Comment by MrFool** [comment]
Doing the merge, turns out after merging master, there are fewer changes than reviewed, i.e. that the number of changes now is < change that was reviewed.

**Pull request merged**
