### PR TITLE
InstructorFeedbackEdit: Apply bootstrap to numerical scale question input box #2829

### LINKED ISSUE #2829: InstructorFeedbackEdit: Apply bootstrap to numerical scale question input box
As per title

### PR DESCRIPTION
**Pull request by JosephineKwa**
Fixes #2829

### CODE REVIEW

**Comment by JosephineKwa** [comment]
What should I do if the test is broken due to a change that I made? Like if I made changes to a html template but the test template did not contain those changes and hence did not pass the test

**Comment by damithc** [comment]
@kanghj for your review please

**Comment by kanghj** [comment]
@JosephineKwa, you need to modify the test html so that the tests pass.

**Comment by JosephineKwa** [comment]
Alright, I have made the necessary changes in the test files. Sorry for the long delay!

**Comment by kanghj** [comment]
Looks good to merge

**Comment by damithc** [comment]
Go ahead and merge @kanghj

**Pull request merged**
