### PR TITLE
New testng config file #3491

### LINKED ISSUE #3491: New testng config file
I made a new testng config file which:
1. Cut the running time by an average of one minute
2. Got me straight dev green at an estimated rate of 1 out of 6 full runs
Here are some proofs:
devgreeeeeen
devgreeeeeen2
devgreeeeeen3
3. Solved some of the existing a-Testing problems
BUT
4. Introduced some new a-Testing problems
I'll just pass it as a new file first. If it is more acceptable to everyone, we can use it as our staple test file and leave a first timer to delete the old file.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #3491

### CODE REVIEW

**Comment by damithc** [comment]
How is this different from the previous one?

**Comment by wkurniawan07** [comment]
Oh right, the diffs are not visible because this is a new file.
1. moved (...)CommentsPageUiTest and InstructorCourseDetailsPageUiTest to parallel
2. moved AdminHomePageUiTest and AllAccessControlUiTests to sequential
Doing 2 solves the long-standing problem of AHPUiTest and AllACUiTest failing due to InvocationTargetException because there are no more session contamination this time.

**Comment by MrFool** [comment]
I believe this fixes #3461, possibly #3456 and possibly #3451

**Comment by wkurniawan07** [comment]
Got a straight dev green again just now

**Comment by damithc** [comment]
Seems fine. Go ahead and replace the old one with this one (as a separate
issue?).  I believe the run configurations are still linked to the old file.

**Comment by wkurniawan07** [comment]
Dr @damithc will do, but is this running fine in live/staging as well? What's working in dev might not work in production.

**Comment by wkurniawan07** [comment]
@MrFool I couldn't say for sure for #3451 and #3456 but I'm very certain this fixes #3459 #3461 and #3486

**Comment by damithc** [comment]
Tried it on dev and live. Seems to be fine.

**Comment by MrFool** [comment]
Let's run this config for the next few days and if any of the issues happen, we comment on them and if they don't, we can remove them since it's probably fixed by this

**Comment by MrFool** [comment]
screen shot 2015-05-25 at 6 06 47 pm

first try, awesome

**Pull request merged**
