### PR TITLE
Update settingUp.md

### PR DESCRIPTION
**Pull request by ngzhian**
I found Step 7 of the prerequisites confusing. The url provided https://developers.google.com/eclipse/docs/using_sdks confused me even more because that was about installing Eclipse SDK, not the GAE SDK.
I realized that I could install the latest GAE SDK using Eclipse's software installation interface, and then specify the older GAE SDK version, which I have downloaded, in the preferences window. Think that is an easier option.
If I'm missing something here, i.e. there's a much simpler way to get GAE SDK v1.9.4 on my com, do tell me, thanks!

### CODE REVIEW

**Comment by junhaoyap** [comment]
Hi Zhi An, thanks for your interest in contributing to Teammates, I've looked through your PR and I get what you mean -

The instructions for installing it is indeed not that intuitive.

In fact, what we are trying to ask people to look at is actually this part ->

screen shot 2015-07-10 at 4 19 43 pm

It is hidden in the middle of the page so I can understand why you didn't see it, I was quite confused when I first set up the project too.

The actual procedure to include the SDK as outlined by the settingUp.md is to download the file from 

https://console.developers.google.com/m/cloudstorage/b/appengine-sdks/o/deprecated/194/appengine-java-sdk-1.9.4.zip

Unzip it and use the 'Add SDK' option to include it via the local computer's directory.

I tried to replicate your solution to no avail, the latest version on Eclipse from Google is only up to 1.9.22 via the plugin download. You might have also downloaded the 1.9.4 version and thus was able to include it?

Perhaps you could give a screenshot of your preferences list and how you managed to include the deprecated version so we could also give it a shot? Or perhaps you could instead, reword the settingUp.md so that newcomers will immediately know what we mean, i.e. to download the zip file, unzip it and add it via the directory.

In any case, apart from that, take a look at https://github.com/TEAMMATES/repo/blob/master/devdocs/process.md where you can get a better idea of how contribution is done. You could open an issue, update settingUp.md (make sure to name your branch appropriately based on the issue) and then open a PR to adhere to it.

Once you're ready and have opened a new PR, you can close this one :) Cheers!

**Comment by ngzhian** [comment]
Thanks for your very detailed explanation, really appreciate it. Will go through your comments and update this PR.
How open are we to including more details in the settingUp.md, e.g. include screenshots and more detailed instructions, rather than just having a URL that points to some (possibly outdated and difficult to read) external documentation?

**Comment by damithc** [comment]
We prefer to keep the documentation 'just enough', for two reasons.
1. Easier maintenance. Screenshots are especially hard to keep up to date.
2. To give new developers a sense of the skill level we expect. We form our first impression of the a new developer based on how much help he/she requires during the set up process. At the same time, the set up process filters out those who are not yet ready for TEAMMATES (i.e. not enough persistence, requires too much hand holding, etc.).

**Comment by ngzhian** [comment]
I disagree slightly with point 2. Setting up your development environment feels like a necessary evil to me, something you need to do to move on to the "interesting bits", which is developing the app. I usually prefer set up to be as easy (and automated) as possible. Set up doesn't feel like a good proxy for the skill level of a new developer. If set up can be made such that it's automatic, a new developer can jump straight to actual development and we will be able to gauge their ability based on their work on the application. Nonetheless I respect that this the rule set forth for this project and will keep this in mind for further contributions :)
As for point 1, definitely agree, I'll work with the contributors to tweak the clarify the instructions in settingUp.md.

**Comment by ngzhian** [comment]
have a newer (and hopefully more compliant pr) #3961, will close this

**Comment by damithc** [comment]
I see your point. We prefer developers who are willing to put up with 'necessary evils' and do not insist on going into the 'interesting bits' right away. Production systems have a lot of necessary evils (maintenance, testing, refactoring etc.) that have to be shared by the developers. There are things one needs to learn during setting up, such as how to IDE configure the IDE to do a certain thing. One doesn't learn much from an automatic setup script. Furthermore, setting up process is where existing developers (even new ones) can help each other because everyone has gone through it. If the setting up is automatic, then those who are not competent enough will get stuck in other issues which require guidance from core developers. That is not a good use of our limited resources.

**Comment by ngzhian** [comment]
Well, there's enough difficult parts in developing systems besides setting
up already. Being the very first step, setting up should be the easier
step. A steep initial learning curve tend to scare new comers away more
than it attract good developers. Furthermore, my observation is that open
source projects usually try to make the initial steps as easy as possible,
but I guess we disagree on where that line is drawn.

If a newcomer gets stuck on the setup, he/she will ask for help anyway, and
take up the time of the core developers, are they going to be ignored so as
to not waste the limited resources? I would prefer they get stuck and ask
for help on issues related to the software rather than at the set up stage

I think we agree that developer time is precious and a project needs good
developers to thrive. However, I think that set up isn't an efficient use
of time, nor is it a good gauge of "competency", whereas you disagree.

Nonetheless, thank you for your answers, I'm glad to hear your point of
view, these are great learning points on maintaining a popular open source
project :)

Best,
Zhi An

**Comment by ngzhian** [comment]
In other news, dev server is up and running, thanks for all your help!

**Comment by damithc** [comment]
Yes, we are not a typical OSS project. We accept contributors because we want to help student developers rise to the next level, not because we want to attract good developers. So it is set up as a boot camp, and as you know, boot camps are not meant to be 'as easy as we can make them'. Our resources are limited, so there is some "self selection" in place. We want to spend our limited resource on those who have potential.  As mentioned, those who get stuck during setting up can get help from other contributors who went through the same thing (an opportunity for existing contributors to shine), not necessarily core developers. Being able to troubleshoot configuration problems is another thing we want students to learn.

**Comment by ngzhian** [comment]
"TEAMMATES - not your typical OSS project" sounds like a good tag line :P
Glad to hear that, excited to learn from all the developers in this project
and will work towards leveling myself up!

Best,
Zhi An

**Pull request closed without merging**
