### PR TITLE
Hard-coded strings in InstructorCourseEditPageUiTest.java #3976

### LINKED ISSUE #3976: Hard-coded strings in InstructorCourseEditPageUiTest.java
There are hard-coded strings like these in __InstructorCourseEditPageUiTest.java__. 

hard-coded string

We need to replace them by constants from `Const.ParamsNames`.

### PR DESCRIPTION
**Pull request by chen-zhuo**
Fixes #3976

### CODE REVIEW

**Comment by kanghj** [comment]
Link to the issue in the pull request's description. "Fixes #..." will create a reference to this pr on the issue so it's easier in future to track our history.

**Comment by chen-zhuo** [comment]
@kanghj edited comment.

**Comment by chen-zhuo** [comment]
Edited comment. @kanghj

**Comment by kanghj** [comment]
Thanks for your contribution, @chen-zhuo.

**Pull request merged**
