### PR TITLE
Spelling mistake in StudentFeedbackQuestionSubmissionEditPage status message #4270

### LINKED ISSUE #4270: Spelling mistake in StudentFeedbackQuestionSubmissionEditPage status message
screen shot 2015-09-11 at 1 56 53 pm

'Successfully' spelt wrongly

### PR DESCRIPTION
**Pull request by unyoungwax**
Fixes #4270

### CODE REVIEW

**Comment by kanghj** [comment]
Thanks for the pr, @unyoungwax! Usually, such a modification will require changes to testing. But since this was categorized as a first-timer issue, the reviewer can change the tests for you before merging.

**Comment by damithc** [comment]
@unyoungwax may be you give it a try first? Run the full test suite, figure out which test cases are failing due to this modification, and modify tests to make them pass.
If you can't figure out, the reviewer can guide to further.

**Comment by unyoungwax** [comment]
I will give it a try.

**Comment by unyoungwax** [comment]
I have updated the related test cases. It is ready for review.

**Comment by kanghj** [comment]
Ok, looks good to me. :+1: Will merge this tomorrow

**Comment by wkurniawan07** [comment]
@kanghj I'll merge this along with my #4606.
@unyoungwax well done for this :+1:

**Pull request merged**
