### PR TITLE
instructor>students tab : format the 'enroll' button differently #2774

### LINKED ISSUE #2774: instructor>students tab : format the 'enroll' button differently
The current one is colored very differently from the background and stands out a bit too much.

### PR DESCRIPTION
**Pull request by bamboo3250**
Fixes #2774

I changed the style of the "Enroll" button.

Before
screenshot_2

After
screenshot_1

Besides, I also changes all the test output files in the test driver so it can pass all the tests.

### CODE REVIEW

**Comment by damithc** [comment]
What happened to the icon? I prefer to keep the icon if possible.

**Comment by bamboo3250** [comment]
@damithc : Does this look okay to you? Please confirm again then I'll start fixing it.
screenshot_3

**Comment by damithc** [comment]
Yes, this one looks good.

**Comment by bamboo3250** [comment]
I updated the new button and fixed the test output files so that it can pass the test.

**Pull request merged**
