### PR TITLE
/admin/stylesheets/teammatesCommon.css not found #2869

### PR DESCRIPTION
**Pull request by ymoctavia**
for #2869

### CODE REVIEW

**Comment by damithc** [comment]
Does this fix the problem?

**Comment by ymoctavia** [comment]
Professor @damithc , I just checked all the admin Pages and found no potential page accessing this url. 

I could not reproduce the error except "directly typing the wrong URL". And this may not be caused by any admin actions, the reason why the icon is red is as follow: 

Currently in PageNotFoundException, the servelet name is decided by 

```
String[] actionTaken = req.getServletPath().split("/");
        String action = req.getServletPath();
        if(actionTaken.length > 0) {
            action = actionTaken[actionTaken.length-1]; //retrieve last segment in path
        }
```

Therefore url like "/admin/wrongpage" will have serveltName in log as "admin", and this will cause the activityLog to have "red admin icon". To solve this, I removed the line which use servletName to check for admin role and only check whether the "role" is admin  .


To conclude, this could be caused by someone directly "typing the URL" and any kind of '/admin/anyWrongPage" URL will produce the same error and this is same for "/page/anyWrongPage"

**Comment by damithc** [comment]
It may be due to the missing slash in src/main/webapp/deadlineExceededErrorPage.jsp
I remember getting the deadline exceed exception while logged in as admin, which match with the times I noticed this error message in the log. Can you add the missing slash in this PR? I asked Ryan to remove that fix from #2849 because it is not related to his issue.

**Comment by ymoctavia** [comment]
Professor @damithc , it is added. But it is strange how this missing "/" will generate URL like "admin/.../.." since the bold text "admin" in red suggests that there must have been a request with this kind of URL.

**Comment by damithc** [comment]
I'm not sure myself. My guess is that the `/` at the start is used to determine where to add `/stylesheets/teammatesCommon.css`. Without the slash, the `stylesheets/teammatesCommon.css` is added to the relative url `https://teammatesv4.appspot.com/admin/`. With the slash, it is added to the base URL which is `https://teammatesv4.appspot.com/`

**Comment by damithc** [comment]
This sounds relevant http://stackoverflow.com/questions/7613274/why-would-a-developer-place-a-forward-slash-at-the-start-of-each-relative-path

**Comment by damithc** [comment]
Doesn't this break some tests?

**Comment by ymoctavia** [comment]
Professor @damithc , the test is fixed

**Pull request merged**
