### PR TITLE
Changed the Tool Tip Message and Placeholder to Guide Instructor in Better way to Search Student 

### PR DESCRIPTION
**Pull request by Doomdev**
Since Both InstructorHome  and InstructorStudentList Search bar Searches all values of the Student in the table ,changed Tool Tip message in Const.Tooltips.SEARCH_STUDENT to new Message and Changed the Placeholder to more readability one.Also Changed Search Button Lable in InstructorHome.jsp from Search to Search Student for better Readability for Instructor . 

s1

s2

k1

k2

### CODE REVIEW

**Comment by franklingu** [comment]
are you sure all tests have passed? but before that, are you sure that the phrasing is clear enough and concise enough?

**Comment by franklingu** [comment]
and also the branch name is not properly named...

**Comment by kanghj** [comment]
Will close. You need to make a new pull request with the right branch name.

**Comment by Doomdev** [comment]
@franklingu The UI test cases includes 2 cases - 1. Tool Tip message for Student Search in InstructorHome.jsp .2. Tool Tip Message for Student Search in InstructorStudentList.jsp Both directs to instructor Search Page where actual Search Results are Displayed .Can you Please  explain more why you have mentioned this statement above :+1:  "are you sure all tests have passed?" ,Is there any other cases I am missing ? . And also is it not that Student Search Searches all values of Student Table ?. Will change the Branch name to Issue2353 and will try to make the Tool Tip message even more clearer and better. I really appreciate your Support / help .Thank you for your patience .

**Pull request closed without merging**
