### PR TITLE
Minor inconsistency in one instructorFeedbackSAll....html file name #3711

### LINKED ISSUE #3711: Minor inconsistency in one instructorFeedbackSAll....html file name
screen shot 2015-06-13 at 11 08 57 pm
screen shot 2015-06-13 at 11 08 50 pm

Self explanatory, I'll fix this along with the other naming consistency issues

### PR DESCRIPTION
**Pull request by MrFool**
Fixes #3711

### CODE REVIEW

**Comment by wkurniawan07** [comment]
On a related note, this naming convention (with 's') actually follows the Java file's. You may want to fix them as well.

**Comment by wkurniawan07** [comment]
On another note, you may want to merge this to `master` instead. Let's not surprise the `master` too much when `JSTL-Dev` is eventually merged. Similar for other HTML inconsistencies.

**Comment by wkurniawan07** [comment]
Good to merge, but like I said before this could be better off in `master` rather than `JSTL-Dev`.

**Comment by MrFool** [comment]
I'll merge those that are currently open / to merge into JSTL-Dev, for the future ones I'll make sure to merge them into master instead, I get what you mean but these are based off an old version of JSTL-Dev and if I merge it into master, master will be contaminated with failing HTMLs :p

**Pull request merged**
