### PR TITLE
 Student profile: 'Email' --> 'Long term contact email' #2906 

### LINKED ISSUE #2906: Student profile: 'Email' --> 'Long term contact email'
Change 'Email' --> 'Long term contact email'

image

### PR DESCRIPTION
**Pull request by ARSPRodrigo**
Fixes #2906

### CODE REVIEW

**Comment by kai33** [comment]
pls also fix StudentProfilePageUiTest

**Comment by LowWeiLin** [comment]
@kai33 or @thyageshm Could either of you review this one?

**Comment by ARSPRodrigo** [comment]
I think there is no need to fix anything in that file. I only change the
text in JSP & HTML files.

On Sun, Mar 8, 2015 at 4:22 PM, KAI XIE <notifications@github.com> wrote:

> pls also fix StudentProfilePageUiTest
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TEAMMATES/repo/pull/3059#issuecomment-77743256>.
>



-- 
*Prasanna Rodrigo,*
*Computer Engineering Undergraduate,*
*Department of Computer Engineering,*

*University of Peradeniya.**+94 720764791*
*::Linkedin <http://lk.linkedin.com/in/prasannarodrigo>*

**Comment by kai33** [comment]
try running that test file in TestNg, if failed, u have to fix it

**Comment by ARSPRodrigo** [comment]
I changed some other files and tests were success. What I have to do now? Commit to the branch "Issue2906" and send another pull request or else?

**Comment by kanghj** [comment]
Commit to the same branch, then this pull request will be updated.

**Comment by ARSPRodrigo** [comment]
Commited.

**Comment by thyageshm** [comment]
could you try and run all the tests and ensure dev is green?

**Comment by ARSPRodrigo** [comment]
Sure.

**Comment by thyageshm** [comment]
just port here once you are done, then I will confirm the commits and merge it in for you.

**Comment by ARSPRodrigo** [comment]
Hi thyageshm,

I'm having some spam problems with running full test. but the unit test of the issue is successful.

**Pull request merged**
