### PR TITLE
 instructorViewStudentRecord: format 'no comments' differently #2772 

### LINKED ISSUE #2772: instructorViewStudentRecord: format 'no comments' differently
Currently, the 'You don't have any comments on this student.' phrase is formatted in the same way we show comments. That could be confusing. Let's format it differently.

### PR DESCRIPTION
**Pull request by ARSPRodrigo**
Fixes #2772

### CODE REVIEW

**Comment by LowWeiLin** [comment]
@ARSPRodrigo Could you try to use italics and gray out the words instead of "list-group-item-info"?
Also, post screenshots of the difference so it is easier to review.

**Comment by LowWeiLin** [comment]
Also, see if you can make the change from the jsp file instead of using javascript.

**Comment by ARSPRodrigo** [comment]
OK, I'll do it.

On Mon, Mar 16, 2015 at 4:18 PM, Low WeiLin <notifications@github.com>
wrote:

> Also, see if you can make the change from the jsp file instead of using
> javascript.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TEAMMATES/repo/pull/3099#issuecomment-81575469>.
>



-- 
*Prasanna Rodrigo,*
*Computer Engineering Undergraduate,*
*Department of Computer Engineering,*

*University of Peradeniya.**+94 720764791*
*::Linkedin <http://lk.linkedin.com/in/prasannarodrigo>*

**Comment by ARSPRodrigo** [comment]
Will this be OK?
issue3099

**Comment by damithc** [comment]
It's still yellowish, and yellow is used for attracting attention. We don't
want to attract attention to this one. Is it possible to use light gray?

**Comment by ARSPRodrigo** [comment]
Like this?
issue3099_2

**Comment by damithc** [comment]
Yes, l like this one.

**Comment by ARSPRodrigo** [comment]
Updated the files.

**Pull request closed without merging**
