### PR TITLE
Change "Received Responses Statistics" to "Statistics for Received Responses" #3245

### PR DESCRIPTION
**Pull request by Doomdev**
Fixes https://github.com/TEAMMATES/repo/issues/3245

### CODE REVIEW

**Comment by LowWeiLin** [comment]
Please read the development process here: https://github.com/TEAMMATES/repo/blob/master/devdocs/process.md

The pull request title and description is wrong. We will not merge or review the pull request if you do not follow the process.

**Comment by Doomdev** [comment]
Oops ,Sorry will change it . :)

**Comment by kanghj** [comment]
Remove the "[" and "]" in the name of the pull request. 

I'm sure "Received Responses Statistics" appears in more than one file, can you check through the different jsp files for the Results page? Also remember to update the tests so that you can get dev green.

**Comment by Doomdev** [comment]
Ok ,,Sure will update the tests till I get dev green and removed [ ] from the pull request .Thank you for Support / help . :+1:

**Comment by kanghj** [comment]
Closing due to inactivity

**Pull request closed without merging**
