### PR TITLE
Add hyphen in feedbackSubmissionsEdit.js at line 175 #4120

### LINKED ISSUE #4120: Add hyphen in feedbackSubmissionsEdit.js at line 175
Got changed in #4002

### PR DESCRIPTION
**Pull request by taniach**
Fixes #4120

### CODE REVIEW

**Comment by kanghj** [comment]
I think you reverted the entire pull request #4011, so can you check if hyphens need to be added to the other lines too?

**Comment by taniach** [comment]
Alright. I think this happened during automatic merging. I don't remember changing question types other than MSQ.

**Comment by taniach** [comment]
How did it get reverted? I merged #4002 before #4011 was created.

**Comment by wkurniawan07** [comment]
This is what happened: take a look at this commit 60834d8 and see what conflicted.

**Comment by taniach** [comment]
@kanghj ready for review

**Pull request merged**
