### PR TITLE
Instructions for setting up can be slightly confusing #3960

### PR DESCRIPTION
**Pull request by ngzhian**
Have a tiny bit more information about where in Preferences they can go to to add the SDK.

### CODE REVIEW

**Comment by ngzhian** [comment]
ref #3940, where the old discussion happened (closes #3940)
pr for #3960

**Comment by junhaoyap** [comment]
@damithc I think that helps to clear up some minor confusion, your take?

**Comment by kanghj** [comment]
@ngzhian, in future don't use "[${issue number}] ${issue title}" as your commit message. We only use that format for merge commits to master, so it may get confusing when we look through git history if you use that format.

**Comment by junhaoyap** [comment]
Oh right, didn't notice the commit message, good catch :)

**Comment by damithc** [comment]
Can merge.

**Comment by junhaoyap** [comment]
@ngzhian before I merge, if it's possible, can you edit the commit message to be just "Update instructions for installing GAE SDK" and set this PR name to be "Instructions for setting up can be slightly confusing #3960".

Do refer to the contributing guide again to understand why, it can be lengthy and a tedious process but it is well worth it in the long run, especially when we need to trace code back to the author.

Afterwards, if you wish to contribute more to Teammates, you can refer to our issues page and start with the simpler ones especially those tagged with "forFirstTimers", "d.Easy" or "forContributors" to get a grasp of Teammates' code base and we will help you along the way if there is a need :)

**Comment by ngzhian** [comment]
@junhaoyap @kanghj thanks for your comments, have updated the PR and the commit message. Went through the contributing guide (process.md) again and noted the requirements, will keep to those practices in the future :)

**Pull request merged**
