### PR TITLE
Migrate devman.html to markdown format #2764

### LINKED ISSUE #2764: Migrate devman.html to markdown format
We can convert devman.html to three files.
```
/devdocs/overview.md
/devdocs/design.md
/devdocs/glossary.md
```

### PR DESCRIPTION
**Pull request by weaveranoop**
Fixes #2764.
This is to migrate devman.html to markdown format. The respective links in README.md are also modified for the same.

### CODE REVIEW

**Comment by kanghj** [comment]
@weaveranoop, follow the format for naming pull requests. Don't make pull requests for issues that are already fixed.

**Comment by weaveranoop** [comment]
@kanghj, sorry about that. I have renamed all the pull requests now. Please have a look on them.

**Comment by LowWeiLin** [comment]
@damithc Some of the formatting may look slightly different, is that okay?

**Comment by damithc** [comment]
Yes, that's ok. Need to remove the original files, but can be done as a separate issue.

**Pull request merged**
