### PR TITLE
student view of contribution question results: use a darker blue for panel heading #2996

### LINKED ISSUE #2996: student view of contribution question results: use a darker blue for panel heading
We use dark blue for things worthy of more attention. This one should be the default dark blue.
image

### PR DESCRIPTION
**Pull request by arvind-kalyan**
Fixes #2996

### CODE REVIEW

**Comment by kanghj** [comment]
For this issue, you should make changes to student view of contribution question results. Although the results page of evaluations and contribution questions have some similarities, this issue is referring to the student's view of contribution questions, which are created in feedback sessions. 

The file, src/main/resources/feedbackQuestionContribResultStatsStudentView.html, contains the html for displaying statistics of contribution question to students.

**Comment by damithc** [comment]
@arvind-kalyan as Hong Jin mentioned 'contribution question results' are generated from two places. This is due to a legacy reason. One place is called 'evaluation results' and the other is called 'feedback session results'. The one one you modified (good job locating it by the way) is the legacy one which is planned to be phased out soon. You can keep those changes. In addition, you need to located the 'feedback session' equivalent and modify that too. Sorry for not mentioning this before.

**Comment by arvind-kalyan** [comment]
Okay.. Will do.

**Comment by arvind-kalyan** [comment]
The encircled in the pic below should be default dark blue, correct?
studentfeedbackresults

**Comment by kanghj** [comment]
The picture you have shows the responses of other students for "Essay" questions. To get a view of "team contribution" question results, you can create a "Team peer evaluation session" on the instructor's sessions page. A Team peer evaluation session is a feedback session that contains a "team contribution" question by default. Then you can log in as a student to give responses to the feedback session, and after you have published the feedback session, you can view the results page as a student. You should see something similar to the screenshot in the original post of the issue.

**Comment by damithc** [comment]
To add, the panels in the screenshot should remain light blue. We use light blue to indicate the 'own responses' (responses submitted by the the user him/herself)

**Comment by arvind-kalyan** [comment]
@kanghj Changes done. Please check.

**Comment by kanghj** [comment]
Looks good too.

**Comment by damithc** [comment]
Go ahead and merge :+1:

**Pull request merged**
