### PR TITLE
Instructor: can add multiple instructors on a course in one step #2890

### LINKED ISSUE #2890: Instructor: can add multiple instructors on a course in one step
Requested by a user. Adding one at a time is troublesome.
Perhaps allow copying multiple instructors from existing courses?

### PR DESCRIPTION
**Pull request by JosephineKwa**
Fixes #2890

### CODE REVIEW

**Comment by JosephineKwa** [comment]
I have implemented the ability to copy instructors from existing courses, however, I have not written tests for it yet. I wanted to check with with you if what I have implemented satisfies the requirements for this issue before writing them. 

The changes made are as shown below:

Instructors are able to select the name, displayed name and access control for the copied instructor. If the blank displayed name is selected, it means that the instructor is not displayed to students.

Also, just for convenience, I added the ability to cancel the adding of an instructor.


In my implementation, I used the pipe character to delimit some input values. Am I allowed to do so, or is there a a way to improve this?

**Comment by damithc** [comment]
The first column should be "Course".
The display name can be a text box (auto filled) rather than a dropdown. It can be any text.
 It's fine if we don't allow copying custom instructors for now. You can create a new issue for that. 
@thyageshm can you review this one?

**Comment by thyageshm** [comment]
sure sir

**Comment by damithc** [comment]
@JosephineKwa Instructor name should be text box as well? It might be better to have email as the 3rd column because course id and email make up the primary identifier for an instructor, so it makes sense to show them side-by-side.

**Comment by JosephineKwa** [comment]
Professor @damithc , about the "courses" column, my intention was actually to display all the courses, delimited by commas,  that the instructor-to-be-copied has been invited to and that the instructor-to-be-copied shares with the logged-in-instructor. 



Thus, I wrote it as "courses" rather than "course". Perhaps I should change it to "course(s)" so that it can be clearer?

Also, since an instructor with a particular email can be in more than 1 course at a time with different names, I put the select box to allow the logged-in-instructor to select which alias he would prefer for the instructor-to-be-copied. Would you prefer if I instead chose one alias and not allow the logged-in-instructor to choose an alias?

I applied this policy for the display name as well. However, if you would prefer to auto-fill the display name text box, what should I fill the text box with?

**Comment by damithc** [comment]
I wonder if it is simpler to show one course/instructor per row. That way,
you can auto fill the name and display columns, which should be text boxes.
Instructor can edit them if required. The access level column can be a drop
down but should contain all access levels except custom. That means
instructors can not only copy past instructors, they can edit some details
at the same time. Furthermore, with this approach it is not hard to copy
instructors with custom access levels too (except in the case of
session/section-level permissions).
The downside is that the list will get long over time. In most cases, the
user will pick from the courses at the top of the list, provided we put
recent courses on top. So the length of the list is not a major issue.

**Comment by JosephineKwa** [comment]
Hmm, I initially decided to collapse all the instructors with the same emails into one row as the course that the instructor is to be copied to uses the email as the primary key (I believe). Hence, the user would not have to explicitly make sure that he avoided selecting instructors with the same email but from different courses. If I do show one course/instructor per row, then the user will have to make sure he does not select two instructors with the same email to copy the details successfully.

**Comment by damithc** [comment]
How is this going?

**Comment by JosephineKwa** [comment]
Professor @damithc , I've been unable to work on this issue these past few days as I have been busy with schoolwork as of late. I will try my best to put out a fix by the end of next Sunday. I am truly sorry about the delay.

**Comment by JosephineKwa** [comment]
Closing for now as it is outdated after JSTL migration.

**Pull request closed without merging**
