### PR TITLE
InstructorHomePageUiTest fails on dev server #2923

### LINKED ISSUE #2923: InstructorHomePageUiTest fails on dev server
Fails at line 161
`homePage.verifyHtmlAjax("/InstructorHomeHTMLWithHelperView.html");`

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #2923 
Dev green and ready for immediate review

### CODE REVIEW

**Comment by wkurniawan07** [comment]
This issue arises due to a combination of two simple yet grave overlooks.

1. Missing `createdAt` field in the JSON data bundle supplied


2. The value of `createdAt` field is not passed from CourseAttributes to Course.
```
    public Course toEntity() {
        return new Course(id, name, Boolean.valueOf(isArchived));
    }
```
In other words, whatever course that is built from the JSON data will be considered newly made as per defined by:
```
    public Course(String courseId, String courseName, Boolean archiveStatus) {
        this.setUniqueId(courseId);
        this.setName(courseName);
        this.setCreatedAt(new Date()); // here is where the problem lies
        this.setArchiveStatus(archiveStatus);
    }
```

I believe these two make the comparison outcome (home page did comparison based on creation date by default) random, and thus the browser page oscillates between this (which makes it pass):

And this (which makes it fail):

**Comment by LowWeiLin** [comment]
The same/similar issue happens in StudentHomePageUiTest as well. See if it can be fixed together?

**Comment by wkurniawan07** [comment]
Hmmm I checked the code for StudentHomePageAction, this page apparently sorted courses based on ID so it's pretty much unaffected by presence/absence of the `createdAt` field.
The one failing StudentHomePageUiTest frequently is the logging in with persistence. I don't think this is related to the fix I made above.

**Comment by LowWeiLin** [comment]
Okay, seems like you don't get the error due to sorting. Will do that in another issue then.

**Comment by wkurniawan07** [comment]
@LowWeiLin managed to solve it in pull request #3260 :+1:

**Pull request merged**
