### PR TITLE
studentFeedbackResults: page title is given as 'submit feedback' #2283

### LINKED ISSUE #2283: studentFeedbackResults: page title is given as 'submit feedback'
I'm referring to the title in the `<head>` section

### PR DESCRIPTION
**Pull request by ruchirsharma1993**
Fixes #2283 
@LowWeiLin 
Sir,
I have closed the last pull request because it already contained the unrelated commit's from another issue. I have then updated my local repository again, and solved the stuff related to this issue. Kindly review and instrcut further steps for this request.

Thanks for the cooperation.

### CODE REVIEW

**Comment by LowWeiLin** [comment]
@ruchirsharma1993 Have you run and passed all tests after the changes?

**Comment by ruchirsharma1993** [comment]
Yes Sir, I have tested with the test cases as well. Few cases are failing on my machine.

**Comment by LowWeiLin** [comment]
StudentFeedbackResultsPageUiTest is failing. Please fix the test.

**Comment by ruchirsharma1993** [comment]
Sir,
I have updated some test files for the StudentFeedbackResultsPageUITest. Please check now.

Thanks

**Pull request merged**
