### PR TITLE
Upgrade jQuery from v1.11.1 to latest v1.11.3 and use CDN #3799

### LINKED ISSUE #3799: Upgrade jQuery from v1.11.1 to latest v1.11.3 and use CDN
Reduces jQuery size as it drops support for IE 6, 7, 8 that is also not officially supported by TEAMMATES along with some bug fixes.

Need to also investigate whether or not we need to update legacy code for upgrading.

### PR DESCRIPTION
**Pull request by junhaoyap**
Fixes #3799 

Uses google's CDN

### CODE REVIEW

**Comment by junhaoyap** [comment]
@bamboo3250 Can help take a look? :)

**Comment by bamboo3250** [comment]
I just ran the test again to make sure. It seems there is no problem with this version :+1:

**Comment by junhaoyap** [comment]
Thanks, appreciated!

**Comment by wkurniawan07** [comment]
Should've been on `master` also. I'll cherry-pick this to `master` then.

**Comment by junhaoyap** [comment]
I don't think this can be cherry picked, I did this on JSTL-Dev because it would require a lot more changes on master due to no templating (yet).

**Comment by wkurniawan07** [comment]
You don't know me well enough if you think I'll stop because of that :stuck_out_tongue:

**Pull request merged**
