### PR TITLE
status message for updating sessions should be green #4191

### LINKED ISSUE #4191: status message for updating sessions should be green
Currently, the status message shown after updating a session is yellow. It should be green.

### PR DESCRIPTION
**Pull request by 526avijitgupta**
Fixes #4191

### CODE REVIEW

**Comment by taniach** [comment]
Please change the test HTMLs also.

**Comment by 526avijitgupta** [comment]
@taniach I could not find any test HTMLs ([here](https://github.com/TEAMMATES/repo/tree/master/src/test/resources/pages)) specific to `InstructorFeedbackEdit` which contain `alert-warning`. Even though there are a few test HTMLs (instructorFeedback*.html) for `instructorFeedback` containing `alert-warning`, but I'm not sure which of them are specific to `instructorFeedbackEdit`.

**Comment by taniach** [comment]
I found that the InstructorFeedbackEditPageUiTest HTMLs do not check the status message for the feedback session successfully updated. Created a separate issue for this.

**Comment by taniach** [comment]
Good job with your first issue :+1:

**Pull request merged**
