### PR TITLE
Some comments don't follow the visibility of the question

### PR DESCRIPTION
**Pull request by franklingu**
for #2949

### CODE REVIEW

**Comment by damithc** [comment]
@kai33 could you review this one?

**Comment by kai33** [comment]
expected visibility controls after added response comment:
screen shot 2015-02-10 at 10 33 45 pm

the actual one after added response comment:
screen shot 2015-02-10 at 10 34 06 pm

One way to fix it is that to refer to the '.responseCommentAddForm'.
if in this form it doesn't have certain rows, then hide them in the form of added response comment.

But even if user ticks the additional checkboxes, it won't break the visibility controls. Since if they cannot view the response, either cannot view response comment.

**Comment by franklingu** [comment]
not following. can you be more specific on this?

**Comment by kai33** [comment]
Hi, so the idea is that:
the visibility options of response comment is actually a subset of its related question's one. So if an option is unchecked in the question's visibility options (eg instructor cannot view this question), then its response comment's visibility options should follow it and cannot override that option. Thus, when display the options for response comment, those unchecked ones (in question's visibility options) should be hidden in the forms of response comment, or otherwise it may confuse the user (because even it's checked, response comment's visibility controls cannot override its question's).

ref: https://docs.google.com/document/d/1YsgDySCOQbLl7Wc5JYPtKqd_hNvGMwea4OqtVOb0HBM/pub?embedded=true#id.w040yumi8t7b
under 'Visibility of Comments for responses', pt 5

**Comment by kai33** [comment]
To solve it (hide the options for response comment according to its question's visibility), one is to use feedbackQuestion object (used by jsp pages), hide the relevant ones based on its visibility. But as it's ajax adding response comment, a suitable way is refer to the web element '.responseCommentAddForm' inside a question. Simply hide the rows in the added comment's visibility that addForm doesn't have.

**Comment by kai33** [comment]
Thank u! merged

**Pull request merged**
