### PR TITLE
JSTL - Standardizing folder organization and such

### PR DESCRIPTION
**Pull request by yj-soh**
Moved tags into a subfolder for instructorHome.
Also made some slight changes to CourseTable to serve as an example for using maps in JSTL.

### CODE REVIEW

**Comment by damithc** [comment]
So we are going with `List<Map<String, String>>`? What about the buttons?

**Comment by yj-soh** [comment]
I believe it's best to keep with the legacy code (of representing them as a HTML block in Java) for the time being and abstract it in the future as an enhancement if necessary.

**Comment by damithc** [comment]
OK, let's do that.

**Comment by damithc** [comment]
can merge.

**Pull request merged**
