### PR TITLE
Show "This session seems to have a large number of responses. ..." message in red #3329

### LINKED ISSUE #3329: Show "This session seems to have a large number of responses. ..." message in red
Otherwise users might miss this message. Currently shown in yellow. Alternatively, we should make normal status messages green so that only warnings like this are in orange.

### PR DESCRIPTION
**Pull request by MrFool**
Partially Fixes #3329

Dirty fix, we could handle the alternative fix for all status message -> green / orange in the future as it will take a larger fix, maybe leave #3329 open.

### CODE REVIEW

**Comment by MrFool** [comment]
screen shot 2015-04-21 at 12 27 53 am

Sample of fix, should be a decent quick fix until we cater to different status types

**Comment by kanghj** [comment]
We do have a way to display status messages in red, by setting the isError variable to true.

**Comment by MrFool** [comment]
Yeah, I saw that variable but the comments stated that it's for 'Whether the execution completed without any errors', I didn't think that having a large number of responses constitutes as an error so I didn't change the variable to true.

However, if that's the way it should be done I can go ahead and change it.

**Comment by damithc** [comment]
May be rephrase the comment slightly so that it fits this situation too?
The situation is not an 'error' but we are unable to perform the requested
action either.

**Comment by MrFool** [comment]
screen shot 2015-05-08 at 6 52 19 pm

Updated with comment and using isError

**Comment by MrFool** [comment]
Got what you mean, updated

screen shot 2015-05-11 at 3 02 41 pm

after latest update

**Comment by damithc** [comment]
@kanghj for review.
@MrFool need to sync with upstream.

**Pull request merged**
