### PR TITLE
JSTL - InstructorStudentRecords

### PR DESCRIPTION
**Pull request by wkurniawan07**
Pending PageData test. Also noticed the merge conflict, will handle after I merge my #3725 into master and master to JSTL-Dev.
Update: de-conflicted and merged with JSTL-Dev, left with PageData test.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
Putting this on hold first as I will reuse some stuff from InstructorComments and maybe InstructorFeedbackResults.

**Comment by wkurniawan07** [comment]
Putting it to on hold again, will reuse stuffs from InstructorCourseStudentDetails

**Comment by junhaoyap** [comment]
Should we re-PR this against master?

**Comment by wkurniawan07** [comment]
Yeah. Closing this one.

**Pull request closed without merging**
