### PR TITLE
Removed useless html files. Fixes #4478

### LINKED ISSUE #4478: Remove unused HTML files
`maintenance.html`: the comparison is removed in 377569f
`instructorFeedbackDoneEditing.html`: the comparison and the file are both removed in 62d8965 but somehow the file survived, should be some merge conflict along the way
`instructorFeedbackResultsSortSecondSessionQuestionSearch.html`: added in b36deab but never used
`studentFeedbackSubmitPageRankSuccess.html`: added in b7b7df4 but never used

### PR DESCRIPTION
**Pull request by yashmehrotra**
As discussed in #4478

### CODE REVIEW

**Comment by kanghj** [comment]
Thanks for the pull request, @yashmehrotra 

Could you have a look at our development process, https://github.com/TEAMMATES/repo/blob/master/devdocs/process.md, and modify the title and description of the pull request (using "Fixes .." automatically closes the issue when the pr is merged)? Note that we reserve commit messages like the one you used for merge commits, so it will be good if you can change your commit message.

**Comment by yashmehrotra** [comment]
I changed the title of the pull request. For the commit should it be `[4478] Removed useless html files. Fixes #4478`

**Comment by wkurniawan07** [comment]
@yashmerotra still wrong. You can have a look at some of the merged PRs here to get an idea of what is required.

**Comment by yashmehrotra** [comment]
Ok. I did not know it was different for contributors and owners. Now I think its the commit message should be `Removed useless html files`.

**Comment by wkurniawan07** [comment]
No, it was no different. The commit format `[1234] Issue title` is reserved for merges to master (it replaces things like `Merge branch "1234-issue-description" to master`.
Also, your PR title and PR description are still both wrong.

**Comment by damithc** [comment]
@yashmehrotra any further progress in this PR?

**Pull request closed without merging**
