### PR TITLE
 Instructor: question edit: Use different color for inner panel titles #2868 

### LINKED ISSUE #2868: Instructor: question edit: Use different color for inner panel titles
Using a different color set them apart from other bold text in the panel. Use the darker tone of the panel background color?

image

### PR DESCRIPTION
**Pull request by NisalaNiroshana**
Fixes #2868

### CODE REVIEW

**Comment by NisalaNiroshana** [comment]
@damithc I have closed the previous pull request and create a new one.Please find the screenshots. As you asked for to  get close to the color used by the 'Preview Visibility' button. I have changed it.
scteammates

**Comment by damithc** [comment]
The color looks fine :+1:

**Comment by kanghj** [comment]
@NisalaNiroshana, remember to update the tests for this page.

**Comment by NisalaNiroshana** [comment]
@kanghj Ok..I will look it and update..Thanks

**Comment by kanghj** [comment]
Closing due to inactivity

**Pull request closed without merging**
