### PR TITLE
Remove maintenance.jsp #3805

### LINKED ISSUE #3805: Remove maintenance.jsp
I read somewhere that past a certain version we no longer need to go through maintenance when deploying new versions of TEAMMATES, if that is true then we no longer need the jsp file for it. Less files to deal with when the eventual importing of before log in is moved into bootstrap and standardization is also done.

### PR DESCRIPTION
**Pull request by MrFool**
Fixes #3805

### CODE REVIEW

**Comment by MrFool** [comment]
@yj-soh can help me with this one? It'll be easy, it's just a removal of a file.

**Comment by yj-soh** [comment]
You may want to remove the constant from `Const.java` as well, or someone may start wondering what's with the extra variable someday in the future.
Aside from that, this probably won't cause any problem anywhere.

**Comment by MrFool** [comment]
Nice, let me work on those :)

**Comment by MrFool** [comment]
Woah thanks for pointing those out, I never knew that page was being tested.

**Comment by MrFool** [comment]
Can be reviewed again!

**Comment by yj-soh** [comment]
Looks fine, should be a good idea to ensure it's dev green before merging, anyway.

**Comment by MrFool** [comment]
Yeap, will never underestimate such changes again :p

**Comment by MrFool** [comment]
Yeah no worries, I ran the test to ensure dev green before I put it back for review after knowing that it was being tested.

**Pull request merged**
