### PR TITLE
InstructorAttributes: findAvailableInstructorGoogleIdForCourse() doesn't return an instructor with 'Co-owner' privilege #3312

### LINKED ISSUE #3312: InstructorAttributes: findAvailableInstructorGoogleIdForCourse() doesn't return an instructor with 'Co-owner' privilege
This issue is related to #3144

### PR DESCRIPTION
**Pull request by tangzijian**
Fixes #3312

### CODE REVIEW

**Comment by damithc** [comment]
@franklingu please review.

**Comment by franklingu** [comment]
You are right to point out that this is the bug. 
https://github.com/TEAMMATES/repo/commit/efcafbc8a0022c35bac04d07e4880aa2eb5b6301

isAllowedForPrivilege is not for testing roles.

however, can we do more than just testing for string equality?

**Comment by tangzijian** [comment]
@franklingu Except testing string of roles, we may check whether the privileges of the instructor match 'Co-owner'?

**Comment by franklingu** [comment]
well, some old instruction object does not have role. can we like use a method to encapsulate this--and prevent exceptions like that

**Comment by kanghj** [comment]
Closing due to inactivity

**Pull request closed without merging**
