### PR TITLE
InstructorFeedbacks: incorrect timezone #3585

### LINKED ISSUE #3585: InstructorFeedbacks: incorrect timezone
wrongtimezone

Our javascript no longers sets the default timezone to be the user's timezone. This is affecting the live server. Caused by commit 24b43197, during the refactoring of the js files.

### PR DESCRIPTION
**Pull request by kanghj**
Fixes #3585

### CODE REVIEW

**Comment by yj-soh** [comment]
Thanks, and sorry.
Do change it to single quotes instead of double, though, to match the style guide.

**Comment by kanghj** [comment]
Done

**Comment by damithc** [comment]
May be @yj-soh can add a test case for this? Make sure the test case fails without the fix.

**Comment by yj-soh** [comment]
I thought about it, but it doesn't seem possible to perfectly cover all the cases.
It's based on JS, so the timezone will depend on the client (unchangeable without some library to mock JS's Date object).
So one way would be to compare the current selection on the page with the client's timezone (gotten via JS), but it would not work if the client's timezone is the default (UTC-12).
This problem would exist as long as the default timezone is possible, but should I commit that anyway? It may be an adequate trade-off with a comment included.

**Comment by damithc** [comment]
That's fine. Most of the developers are in SG timezone anyway so the test will work for most of us :-)

**Comment by kanghj** [comment]
Looks good to me

**Pull request merged**
