### PR TITLE
 Instructor: question edit: Use different color for inner panel titles #2868 

### LINKED ISSUE #2868: Instructor: question edit: Use different color for inner panel titles
Using a different color set them apart from other bold text in the panel. Use the darker tone of the panel background color?

image

### PR DESCRIPTION
**Pull request by NisalaNiroshana**
Fixes #2868

### CODE REVIEW

**Comment by LowWeiLin** [comment]
@NisalaNiroshana Could you post a screenshot of the changes? Thanks!

**Comment by NisalaNiroshana** [comment]
@LowWeiLin Here is a screenshot..thanks
teammates

**Comment by damithc** [comment]
it is the bold words that should be in a different color, not the question within paranthesis. Try the darker shade of the panel background color. Post another screenshot after changing.

**Comment by NisalaNiroshana** [comment]
Is this ok ?? 
screenshot from 2015-03-24 09 24 15

**Comment by damithc** [comment]
Can you get close to the color used by the 'Preview Visibility' button?

**Comment by NisalaNiroshana** [comment]
@damithc  Ok sure

**Comment by NisalaNiroshana** [comment]
I closed this pull request and create another one..please review it..#3194

**Pull request closed without merging**
