### PR TITLE
Change cursor to pointer for the [Edit] link in the comments for the create feedback form #2301

### LINKED ISSUE #2301: Change cursor to pointer for the [Edit] link in the comments for the create feedback form
Found in instructorFeedbacksPage and instructorFeedbackEditPage

### PR DESCRIPTION
**Pull request by ZiXian92**
Fixes #2301

### CODE REVIEW

**Comment by LowWeiLin** [comment]
I'm not sure if we want/need to apply the pointer cursor to all <a> links across teammates. It does makes some sense however. @damithc should we apply the pointer cursor to just this [Edit] link or in all places?

**Comment by damithc** [comment]
Shouldn't that be the default? Not sure why it doesn't work in this
particular instance. In any case, let's apply it for this instance only, to
be safe. If we detect more places with similar problems, we can think of
applying it site-wide.

**Comment by ZiXian92** [comment]
Ok. Since the 2 cases share the same id, I can apply the CSS setting to that id.

**Comment by ZiXian92** [comment]
Pushed out the new changes.

**Comment by LowWeiLin** [comment]
Great! Looks good to merge.

**Comment by damithc** [comment]
@LowWeiLin you'll have to merge yourself. @ZiXian92 doesn't have push permissions.

**Pull request merged**
