### PR TITLE
Remove destination parameter in AjaxResult #3834

### LINKED ISSUE #3834: Remove destination parameter in AjaxResult
As mentioned in the todo here:
ajaxresult

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #3834

### CODE REVIEW

**Comment by MrFool** [comment]
The changes are ok, will run the tests over lunch to ensure dev green, have any idea why the destination params is not used at all though?

**Comment by wkurniawan07** [comment]
The destination param is a .jsp template. Ajax result needs no such thing :stuck_out_tongue:

**Comment by MrFool** [comment]
I see, so Ajax results just need the this.data = data which "passes the data", something like that?

**Comment by MrFool** [comment]
Ok to merge, dev green when I ran the tests

**Pull request merged**
