### PR TITLE
Long test account IDs will fail some specific tests #4372

### LINKED ISSUE #4300: Add godmode fixes for admin test changes
Remnants of #4262, @LowWeiLin and I didn't want to rush through the godmode changes in time for the milestone as it might not be done well!

### LINKED ISSUE #4372: Long test account IDs will fail some specific tests
Some time back there's an issue with overly long `${test.admin}` failing tests. Surprisingly, all these other similar culprits managed to escape our sights:
- Long `${test.instructor}` -> `InstructorCourseJoinConfirmationPageUiTest` fails
- Long `${test.student1}` -> `StudentCourseJoinConfirmationPageUiTest` fails
- Long `${test.unreg}` -> `StudentHomePageUiTest` fails

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #4372, fixes #4300 (related issue), and closes #4323 (no longer needed).
@junhaoyap tagging you for your interest

### CODE REVIEW

**Comment by thyageshm** [comment]
The fix looks good. Just a few things to ensure:
1. Are these the only pages?
2. Does GodModeTest test this?
3. Do we test the truncation of names elsewhere to ensure that the truncation does happen as expected? Since we are combining the two here, we must ensure that there are other places that we check that this feature is being covered by tests

**Comment by wkurniawan07** [comment]
1&3. Tested on the full run with long IDs on all 5 accounts, worked fine.
2. Added test cases on GodModeTest.

**Comment by thyageshm** [comment]
Great! the files look good.

Just to clarify what I asked in (3), I meant whether we test the truncation of ids anywhere. Like now that the placeholder is the same for truncated and non-truncated ids, do we still have a test that checks that? If not we need to add an explicit test that ensures that long ids are truncated as expected

**Comment by wkurniawan07** [comment]
The files I mentioned in #4372 and the admin UI tests, if they haven't been deleted or are not going to be deleted, will test those.

**Comment by thyageshm** [comment]
I dont think they will. Now that Godmode substitutes both with the same placeholder, they will not fail even if the truncation does not fail

**Comment by wkurniawan07** [comment]
Hmmmm let me get this clear, is the issue here about testing whether truncation _does_ happen? Then no it's not handled here. If we really go down that path, then I think the only solution is the `${test.truncatedAccount}`.
I don't think this is that big of an issue because the truncation is really only for displaying purpose. But not hard to fix.

**Comment by thyageshm** [comment]
You are right, I am asking whether we test whether the truncation is happening. If we know that truncation definitely happens in one of the tests, we can have a non-html-compare test to simply test it out. We dont need the ${test.truncatedAccount} for it :-)

**Comment by wkurniawan07** [comment]
`StringHelperTest` already tests it. It's not specific to `truncateLongId`, but the general `truncate` function, but if the latter works then the former should work, no?

**Comment by thyageshm** [comment]
I think it might still be needed :-/ You are right that it should work, but by testing it at the browser test level we are ensuring that the correct methods are being called.
A quick test of the value in the span to the expected truncated value would be great.

**Comment by wkurniawan07** [comment]
I still don't see why. If really needed I'll just add one line in `GodModeTest`.

**Comment by damithc** [comment]
StringHelperTest is a unit test. What we need here is an integration test. The method might work but what if it was not called from where it should be called?

**Comment by wkurniawan07** [comment]
I just realized `${test.truncatedAccount}` doesn't solve the issue. Anyway, if truncation is not called where it's supposed to be, imo it's no big deal since it's purely cosmetic (like seeing veryveryveryveryverylongid instead of veryveryveryveryvery...) and the chance of anyone having google id that long is not that high. Not test breaking, not poisonous in any manner. And as far as I know it's always called whenever needed.

**Comment by damithc** [comment]
long google id's are not that rare. Google allows using a whole non-gmail email address as the Google ID.
Yes, the functionality is not critical. So if it hard to test, no need to test it. Is it hard to test?

**Comment by wkurniawan07** [comment]
I just thought of an easy way. But need to wait until I get back, I'm quite far from where my laptop is for the next few hours.

**Comment by wkurniawan07** [comment]
I modified the google ids of two UI test cases (one student, one instructor) to be a very long one to ensure that they are truncated. I picked the shortest tests that I can find to minimize the changes. Unfortunately I can't test the admin side because the admin username is injected from `test.properties`, but this shouldn't be a big deal.

**Comment by thyageshm** [comment]
Great!

**Pull request merged**
