### PR TITLE
Scroll to the edited question when instructors wants to moderate for one specific response #3290

### LINKED ISSUE #3290: Scroll to the edited question when instructors wants to moderate for one specific response
Currently, when instructor clicks on the 'Moderate' button for one specific response in the feedback results page, it will redirect to the feedback edit page without scrolling to the specific question which needs to have responses edited

### PR DESCRIPTION
**Pull request by acruis**
Fixes #3290 

The initial commits are for program logic, but the bulk of the lines changed are from updating test cases.

For testing, out of 23 HTML files used in InstructorFeedbackResultsPageUiTest, 12 files were updated. The only change to these files were the addition of an `<input name="moderatedquestion" type="hidden" value="{*}"/>` element for every `Moderate Response` button that originates from a specific question. (hence only the Questions and Recipient > Question > Giver views were affected)

Generating the updated files was done through a separate script which can be found [here](https://github.com/acruis/samples/blob/master/TestAppend.java). For the code reviewer, instead of checking the diff in every test file, you can simply check the logic of the generator script and then run the script on the original HTML files to check that the outcome matches the new files in this PR.

### CODE REVIEW

**Comment by damithc** [comment]
@LowWeiLin can review this one?

**Comment by LowWeiLin** [comment]
ok

**Comment by LowWeiLin** [comment]
The code seems correct, but the tests are failing after merging with master branch.

**Comment by acruis** [comment]
Probably because of other changes to the same page's UI from other PRs. I'll merge from master and run the script again.

**Comment by MrFool** [comment]
Closing this, refer to #3428 for the continuation of this PR

**Pull request closed without merging**
