### PR TITLE
Too many variations of JSP pertaining to page body and body header #3674

### LINKED ISSUE #3674: Too many variations of JSP pertaining to page body and body header
Here are some of the different variations:

screen shot 2015-06-10 at 1 28 10 pm
screen shot 2015-06-10 at 1 27 59 pm
screen shot 2015-06-10 at 1 27 35 pm
screen shot 2015-06-10 at 1 27 24 pm
screen shot 2015-06-10 at 1 27 13 pm
screen shot 2015-06-10 at 1 27 02 pm

We should standardise it via a separate branch off the JSTL development branch or else there will be a lot more HTML changes than we want.

I can investigate which actually renders the pages correctly and get back to everyone before tomorrow's scrum / standardise it.

### PR DESCRIPTION
**Pull request by MrFool**
Fixes #3674

### CODE REVIEW

**Comment by MrFool** [comment]
Don't review yet, I'll be splitting the PRs up, especially for pages that "seems" to have alot of changes, they actually don't but I'll explain why in the smaller PRs and revert their changes in this PR.

**Comment by wkurniawan07** [comment]
Finally someone else did it. Now you know why I'm taking a break from #3588. Those damn 6 UI tests.

**Comment by MrFool** [comment]
Notes to reviewer:

1. instructorCourseJoinConfirmation & studentCourseJoinConfirmation page has a different template so don't expect the same

2. unregisteredStudentFeedbackResultsPageMCQ.html has more changes because it is full verification and because of the standardization there is a huge indent change of the HTML generated.

**Comment by MrFool** [comment]
The new standardized format is the following:

<code>
<div class="container" id="frameBodyWrapper">
    <div id="topOfPage"></div>
    <h1>Submit Feedback Question</h1>
    <br>
</code>

For now let's use this as this requires the least amount of changes for us to move forward, eventually we want to remove frameBodyWrapper as it is no longer being used and also use bootstrap's "page-header" class to enhance UI for usability due to it helping to add a segmentation between title and page content, but we can do that after JSTL is completed. By then we'll only need to change up the template and it'll be all good instead of having to change over hundreds of files like now.

**Comment by MrFool** [comment]
This one is finally ready for review, just checked for dev green.

**Comment by MrFool** [comment]
Also made a check on the file with a lot of changes, but I need someone else to help double check :)

**Comment by damithc** [comment]
Eyeballing required. May be you guys can split up such work and take turns :-)

**Comment by MrFool** [comment]
Indeed, I eyeballed everything once, but 1 person (especially since I did the issue) can't be trusted for this :p help please :D

**Comment by kanghj** [comment]
Eyeballed through it and it looks good to me

**Comment by wkurniawan07** [comment]
Looks good to me too.

**Pull request merged**
