### PR TITLE
Update contributor list

### PR DESCRIPTION
**Pull request by LowWeiLin**
Updated contributor list:

Chi Cheng
Devang Gaur
Gu Junchao
Han Zijian
Josephine Kwa
Kang Hong Jin
Manvi Jain
Qua Zi Xian
Ryan Chang
Subhodip Kumar
Svitlana Nesterenko
Tang Ning
Tania Chattopadhyay
Yang Mo

### CODE REVIEW

**Comment by damithc** [comment]
Some of these guys (Gu Junchao, Hong Jin, Yang Mo) are in the core team or committer list. They should not be in the contributor list.

**Comment by LowWeiLin** [comment]
So do i remove them? there are others in the core team/commiter list for are also in the contributor list.

**Comment by damithc** [comment]
Yes, any name should not appear in more than one place.

**Comment by damithc** [comment]
Contributors list (multiple contributions) and Contributors (single contribution) should be in alphabetical order too. A few names don't seem to follow that order.

**Comment by damithc** [comment]
Another duplicate: Tania is also in the 'single contribution' list.

**Comment by LowWeiLin** [comment]
Are both Tania the same person? The one in 'single contribution' list
contributed when we were using google code.
I wasn't sure so I left that one there.

**Comment by LowWeiLin** [comment]
Okay i just checked, it is a duplicate.

**Comment by LowWeiLin** [comment]
Removed duplicates @damithc

**Pull request merged**
