### PR TITLE
instructor view results: contribution question, giver column sorting is broken #3346

### LINKED ISSUE #3346: instructor view results: contribution question, giver column sorting is broken
See screenshot. This is the 'by question' view. May be broken in other places too. Also need to add missing tests to catch it.

image

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #3346 
Refer to the issue thread for explanation.

### CODE REVIEW

**Comment by kanghj** [comment]
Add a test for this?

**Comment by wkurniawan07** [comment]
I think it's not possible, considering the origin of the issue:

Previously, failure will occur if the hash values in the studentemail field messed up the alphabetical order (since `.innerHTML` will also capture them in the compared strings). To replicate this, we need to actually determine the hash values before hand, which I don't think is possible.
`.innerText` ignores any HTML wrapper and goes straight to the string, which solves the problem.

**Comment by kanghj** [comment]
Use selenium to click on the column to sort the table, then verify that the column is sorted correctly? <code>AppPage.verifyTablePattern</code> can be used

**Comment by wkurniawan07** [comment]
That already has a test in `InstructorFeedbackResultsPageUiTest`. This bug escaped the test because, well, hash values are random.

**Pull request merged**
