### PR TITLE
AddSectionsToLargeCourses is too slow #3402

### LINKED ISSUE #3402: AddSectionsToLargeCourses is too slow
Make it faster

### PR DESCRIPTION
**Pull request by kanghj**
Fixes #3402

### CODE REVIEW

**Comment by damithc** [comment]
Did some minor tweaks. However, the code doesn't seem to work for me. For some reason `logic.getStudentsForTeam(teamName, courseId)` returns zero results, so the script returns without doing anything.

**Comment by kanghj** [comment]
Works on the staging server for me.

**Comment by kanghj** [comment]
Updated to not use <code> logic.getStudentsForTeam </code>

**Comment by damithc** [comment]
migration completed. can merge.

**Pull request merged**
