### PR TITLE
Show shortname with the photo. #2431

### PR DESCRIPTION
**Pull request by thyageshm**
@damithc  sir, the basic implementation is done. Test addition/update is left to be done.

Also, the picture/shortname are not shown by default. They require a hover-and-click to get loaded and later to be shown they need a hover action from user. Would you like another place where I show the shortnames/pics when an instructor begins to comment?

### CODE REVIEW

**Comment by damithc** [comment]
Ideally, it should load automatically into somewhere near the comment box, but I'm not sure how hard it is to do. Also, show both full name and short name? Some might not have a short name.
image

**Comment by thyageshm** [comment]
image

something like this? the format is:
                                giver ; recipient

**Comment by damithc** [comment]
I think it is better to say 'from: Alice to: Danny' if there are no short
names, can use full name. I don't mind if you load the photo as well, if
that can be managed.

**Comment by thyageshm** [comment]
photos in the same place as the names?

**Comment by damithc** [comment]
Yes.

**Comment by kanghj** [comment]
Since now we are using JSTL, this needs to be redone. Closing for now

**Pull request closed without merging**
