### PR TITLE
instructor: session edit: Add one more blank row to new rubric questions #2873

### LINKED ISSUE #2873: instructor: session edit: Add one more blank row to new rubric questions
Currently we have one row with sample values. We can add one more blank row to make it look more like a typical rubric question.
image

### PR DESCRIPTION
**Pull request by JosephineKwa**
Fixes #2873

### CODE REVIEW

**Comment by JosephineKwa** [comment]
Here is the change made to the UI

screenshot 38

**Comment by kanghj** [comment]
Looks good.

**Comment by damithc** [comment]
@LowWeiLin could you do a quick check? If no issues, @kanghj can merge.

**Comment by LowWeiLin** [comment]
Looks good to me.

**Pull request merged**
