### PR TITLE
Regenerate HTML files with God mode

### PR DESCRIPTION
**Pull request by wkurniawan07**
Not sure if it is wise to include everything altogether though. But if we ever want to utilize God mode again, we need to get the current HTML files up to God mode's standard.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
I'll push my modified god mode here, maybe a few of you can run the whole test suite with it and see if there are still diffs generated?

**Comment by wkurniawan07** [comment]
Anyway, to use modified God mode, nothing needs to be done. Once the HTML verification passes the HTML file will be regenerated via God mode (as opposed to God mode which regenerates after verification failure). Quite convenient.
P.S. the fourth commit will be part of another issue.

**Comment by wkurniawan07** [comment]
@junhaoyap here, just pull the code and run the test, no need to add anything

**Comment by wkurniawan07** [comment]
going to interactive-rebase this to tidy up, anyone who owns a local copy of this do take note :sweat_smile:

**Comment by junhaoyap** [comment]
Running this to test atm, will let you know once it is done.

**Comment by junhaoyap** [comment]
screen shot 2015-07-09 at 11 14 47 am
screen shot 2015-07-09 at 11 14 39 am

I didn't fail the thing that tania failed, but I didn't manage to pass this, isn't key supposed to be wildcard?

It's the only test that I failed.

**Comment by junhaoyap** [comment]
Oops, didn't notice the PR runs godmode automatically, yes I got the same problem as Tania but I think that's ok because the test still passes on either way - whether we have the line breaks or not.

**Comment by damithc** [comment]
Running godmode automatically is part of the solution. What's the follow up action? Go through the changes and commit the relevant ones? If the god mode keeps overwriting wildcards, it's going to be troublesome.

**Comment by wkurniawan07** [comment]
Dr @damithc after the improvements I made, there are only two important wildcards that are overwritten by God mode: one in `login.html` (#3374) and another `studentCourseJoinConfirmationHTML.html` (#3499). A small price to pay, I guess?
Anyway, I'm not including the automatic God mode as part of the merge. If we ever want to do that, a separate PR is to be called for.

**Comment by wkurniawan07** [comment]
Not auto-closed since I'm excluding the last commit :s
Anyway, closing words:
1. We can finally use God mode again. Yay!
2. If anyone has the urge to re-use the modified God mode for any reason, just cherry-pick from branch `ModifiedGodMode`.

**Pull request closed without merging**
