### PR TITLE
Too many variations of JSP pertaining to page body and body header (InstructorCourseEdit specific) #3685

### LINKED ISSUE #3685: Too many variations of JSP pertaining to page body and body header (InstructorCourseEdit specific)

### PR DESCRIPTION
**Pull request by MrFool**
Fixes #3685 

Manually done

### CODE REVIEW

**Comment by MrFool** [comment]
checked, dev green

**Comment by damithc** [comment]
@kanghj another one for arrowing :-)

**Comment by bamboo3250** [comment]
ok, this looks good.

**Comment by bamboo3250** [comment]
I'll merge this PR into my PR #3677 first

**Pull request merged**
