### PR TITLE
Request.html does not have a link back to Features.html #1151

### LINKED ISSUE #1151: Request.html does not  have a link back to Features.html
_From [KAGEN...@gmail.com](https://code.google.com/u/106767547685865768379/) on August 22, 2013 21:09:41_

I understand that the Request for an Account page is part of the feature page. 
However, I feel that the user should be able to return to the features page by pressing the features tab by pressing the tab. Instead of using the browser back function

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1152_

### PR DESCRIPTION
**Pull request by Maroooon**
Fixes #1151

### CODE REVIEW

**Comment by LowWeiLin** [comment]
The pull request title is in the wrong format, and the description is also wrong. See: https://github.com/TEAMMATES/repo/blob/master/devdocs/process.md

**Comment by LowWeiLin** [comment]
Also, remove changes unrelated to the issue.

**Comment by Maroooon** [comment]
Restored the files unrelated to the Issue.
The files request.html~ and teammates.css~ are just temporary files created as backup of the original files in case someone wants to refer the original files.

**Comment by LowWeiLin** [comment]
We don't need the original files. We have git for that. Please remove those as well.

**Comment by Maroooon** [comment]
Hey Low Checkout out the new Commit...

**Pull request merged**
