### PR TITLE
Add full HTML check for InstructorStudentList, InstructorStudentRecords, and StudentCourseDetails UI test #4373

### LINKED ISSUE #4373: Add full HTML check for InstructorStudentList, InstructorStudentRecords, and StudentCourseDetails UI test
The first two is now possible because of #4359. The last one is noted in a TODO, might as well do it now.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #4373 
Explanation for `InstructorStudentList`: the previous "full check" is a false positive because it's actually checking `InstructorSearchPage`, and this has been done in its own UI test.

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@junhaoyap I hope you don't mind reviewing! Just use the "?w=1" thingy and this shouldn't be hard :smile:

**Comment by junhaoyap** [comment]
Sure, give me 2 days, I'm in the middle of a hackathon right now ;) If it's too long to wait might wanna give someone else >.<

**Comment by wkurniawan07** [comment]
No worries, no rushing here.

**Comment by junhaoyap** [comment]
Sorry, finally had time to look through this, having crunch time at the moment, but it looks good to merge!

**Pull request merged**
